#
# Unified Query Algebra
#
# Copyright (c) 2023-2026 Cognica, Inc.
#

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable, Generator, Literal, Mapping, Protocol, Sequence, TypedDict

Scalar = None | bool | int | float | str | bytes | list["Scalar"] | dict[str, "Scalar"]
FunctionVolatility = Literal["volatile", "stable", "immutable"]

class SQLParam:
    @staticmethod
    def scalar(value: Scalar) -> SQLParam: ...
    @staticmethod
    def vector(values: Sequence[float]) -> SQLParam: ...
    @staticmethod
    def tensor(values: Sequence[Sequence[float]]) -> SQLParam: ...

class SQLNotice(TypedDict):
    level: Literal["DEBUG", "LOG", "INFO", "NOTICE", "WARNING"]
    sqlstate: str
    message: str
    detail: str | None
    hint: str | None

class SQLResult:
    @property
    def columns(self) -> list[str]: ...
    @property
    def rows(self) -> list[dict[str, Scalar]]: ...
    @property
    def affected_rows(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

class HttpSQLStream:
    @property
    def request_id(self) -> str: ...
    def next_frame(self) -> dict[str, Any] | None: ...
    def __iter__(self) -> HttpSQLStream: ...
    def __next__(self) -> dict[str, Any]: ...

class NotificationSubscriptionOptions:
    def __init__(self, *, max_active_subscriptions: int, max_channels: int, max_queued_notifications: int, max_queued_bytes: int, max_registry_entries_per_poll: int) -> None: ...

class NotificationRetryOptions:
    def __init__(self, *, max_attempts: int, episode_timeout_ms: int, initial_backoff_ms: int, max_backoff_ms: int, max_retry_after_ms: int) -> None: ...

class HttpNotificationOptions:
    def __init__(self, *, max_channels: int, max_queued_events: int, max_queued_bytes: int, max_transport_chunk_bytes: int, connect_timeout_ms: int, ready_timeout_ms: int, max_idle_timeout_ms: int, retry: NotificationRetryOptions | None = None) -> None: ...

class NotificationEvent:
    @property
    def kind(self) -> Literal["notification", "resync_required", "reconnected"]: ...
    @property
    def epoch(self) -> str: ...
    @property
    def request_id(self) -> str | None: ...
    @property
    def sequence(self) -> int | None: ...
    @property
    def process_id(self) -> int | None: ...
    @property
    def channel(self) -> str | None: ...
    @property
    def payload(self) -> str | None: ...
    @property
    def cause(self) -> str | None: ...

class NotificationFailure:
    @property
    def code(self) -> str: ...
    @property
    def original_failure(self) -> NotificationFailure | None: ...
    @property
    def last_attempt_failure(self) -> NotificationFailure | None: ...
    @property
    def http_status(self) -> int | None: ...
    @property
    def diagnostic(self) -> str | None: ...

class NotificationError(RuntimeError):
    code: str
    failure: NotificationFailure

class NotificationSubscription:
    @property
    def epoch(self) -> str: ...
    @property
    def request_id(self) -> str | None: ...
    @property
    def is_closed(self) -> bool: ...
    def next_event(self) -> NotificationEvent | None: ...
    def close(self) -> None: ...
    def __iter__(self) -> NotificationSubscription: ...
    def __next__(self) -> NotificationEvent: ...
    def __enter__(self) -> NotificationSubscription: ...
    def __exit__(self, exc_type: Any, exc: Any, traceback: Any) -> bool: ...

class AsyncNotificationSubscription:
    @property
    def epoch(self) -> str: ...
    @property
    def request_id(self) -> str | None: ...
    @property
    def is_closed(self) -> bool: ...
    def __aiter__(self) -> AsyncNotificationSubscription: ...
    async def __anext__(self) -> NotificationEvent: ...
    async def aclose(self) -> None: ...
    async def __aenter__(self) -> AsyncNotificationSubscription: ...
    async def __aexit__(self, exc_type: Any, exc: Any, traceback: Any) -> bool: ...

class _AsyncNotificationRegistration:
    def __await__(self) -> Generator[Any, None, AsyncNotificationSubscription]: ...
    async def __aenter__(self) -> AsyncNotificationSubscription: ...
    async def __aexit__(self, exc_type: Any, exc: Any, traceback: Any) -> bool: ...

class HttpEngineError(RuntimeError):
    code: str | None
    status: int | None
    request_id: str | None
    diagnostic: dict[str, str | int | None] | None

class HttpEngine:
    def __init__(self, url: str, token: str) -> None: ...
    @staticmethod
    def from_env() -> HttpEngine: ...
    @staticmethod
    def local(project: str, *, cli_path: str | Path | None = None) -> HttpEngine: ...
    @staticmethod
    def cloud(
        project: str,
        organization: str | None = None,
        *,
        cli_path: str | Path | None = None,
    ) -> HttpEngine: ...
    def sql(self, query: str, params: Sequence[Scalar | SQLParam] | None = None) -> SQLResult: ...
    def execute(self, query: str, params: Sequence[Scalar | SQLParam] | None = None) -> SQLResult: ...
    def sql_with_metadata(
        self,
        query: str,
        params: Sequence[Scalar | SQLParam] | None = None,
    ) -> tuple[SQLResult, str]: ...
    def sql_batch(self, statements: Sequence[tuple[str, Sequence[Scalar | SQLParam]]]) -> list[SQLResult]: ...
    def sql_batch_with_metadata(
        self,
        statements: Sequence[tuple[str, Sequence[Scalar | SQLParam]]],
    ) -> tuple[list[SQLResult], str]: ...
    def sql_stream(
        self,
        query: str,
        params: Sequence[Scalar | SQLParam] | None = None,
    ) -> HttpSQLStream: ...
    def subscribe_notifications(self, channels: Sequence[str], *, options: HttpNotificationOptions) -> NotificationSubscription: ...
    def subscribe_notifications_async(self, channels: Sequence[str], *, options: HttpNotificationOptions) -> _AsyncNotificationRegistration: ...

class Engine:
    def __init__(self) -> None: ...
    def subscribe_notifications(self, channels: Sequence[str], *, options: NotificationSubscriptionOptions) -> NotificationSubscription: ...
    def subscribe_notifications_async(self, channels: Sequence[str], *, options: NotificationSubscriptionOptions) -> _AsyncNotificationRegistration: ...
    @staticmethod
    def open(path: str | Path) -> Engine: ...
    @staticmethod
    def open_encrypted(path: str | Path, key: str) -> Engine: ...
    @staticmethod
    def open_auto(path: str | Path, key: str | None = None) -> Engine: ...
    @staticmethod
    def detect_database_file(path: str | Path) -> str: ...
    @staticmethod
    def open_compressed(
        path: str | Path,
        codec: str = "zstd",
        page_size: int | None = None,
        chunk_pages: int | None = None,
        level: int | None = None,
    ) -> Engine: ...
    @staticmethod
    def open_compressed_encrypted(
        path: str | Path,
        key: str,
        codec: str = "zstd",
        page_size: int | None = None,
        chunk_pages: int | None = None,
        level: int | None = None,
    ) -> Engine: ...
    def sql(self, query: str, params: Sequence[Scalar | SQLParam] | None = None) -> SQLResult: ...
    def execute(self, query: str, params: Sequence[Scalar | SQLParam] | None = None) -> SQLResult: ...
    def sql_batch(self, statements: Sequence[tuple[str, Sequence[Scalar | SQLParam]]]) -> list[SQLResult]: ...
    def register_scalar_function(
        self,
        name: str,
        callable: Callable[..., Scalar],
        *,
        volatility: FunctionVolatility = "volatile",
        may_mutate_engine: bool = True,
    ) -> None: ...
    def register_table_function(
        self,
        name: str,
        callable: Callable[..., TableResult],
        *,
        volatility: FunctionVolatility = "volatile",
        may_mutate_engine: bool = True,
    ) -> None: ...
    def register_aggregate_function(
        self,
        name: str,
        factory: Callable[[], AggregateState],
        *,
        volatility: FunctionVolatility = "volatile",
        may_mutate_engine: bool = True,
    ) -> None: ...
    def create_default_table(self, name: str, fts_fields: Sequence[str]) -> None: ...
    def create_vector_field(self, table: str, field: str, dimensions: int) -> bool: ...
    def add_document(self, table: str, doc_id: int, document: Mapping[str, Scalar]) -> None: ...
    def add_document_with_vectors(
        self,
        table: str,
        doc_id: int,
        document: Mapping[str, Scalar],
        vectors: Mapping[str, Sequence[float] | Sequence[Sequence[float]]],
    ) -> None: ...
    def add_vector(self, table: str, doc_id: int, field: str, vector: Sequence[float]) -> bool: ...
    def add_vector_values(self, table: str, doc_id: int, field: str, vectors: Sequence[Sequence[float]]) -> bool: ...
    def get_document(self, table: str, doc_id: int) -> dict[str, Scalar] | None: ...
    def delete_document(self, table: str, doc_id: int) -> None: ...
    def document_count(self, table: str) -> int: ...
    def search(self, table: str, field: str, query: str, top_k: int = 10, scoring: str = "bm25") -> list[dict[str, float | int]]: ...
    def knn_search(self, table: str, field: str, vector: Sequence[float], top_k: int = 10) -> list[dict[str, float | int]]: ...
    def vector_similarity_search(self, table: str, field: str, vector: Sequence[float], threshold: float) -> list[dict[str, float | int]]: ...
    def hybrid_search(
        self,
        table: str,
        text_field: str,
        text_query: str,
        vector_field: str,
        query_vector: Sequence[float],
        top_k: int = 10,
        knn_pool: int | None = None,
    ) -> list[dict[str, float | int]]: ...
    def robust_hybrid_search(
        self,
        table: str,
        text_field: str,
        text_query: str,
        vector_field: str,
        query_vector: Sequence[float],
        top_k: int = 10,
        knn_pool: int | None = None,
        alpha: float = 0.5,
    ) -> list[dict[str, float | int]]: ...
    def estimate_scoring_params(
        self,
        table: str,
        field: str,
        n_samples: int = 50,
        tokens_per_query: int = 5,
        seed: int = 42,
    ) -> dict[str, float]: ...
    def learn_scoring_params(self, table: str, field: str, query: str, labels: Sequence[int]) -> dict[str, float]: ...
    def update_scoring_params(self, table: str, field: str, score: float, label: int) -> None: ...
    def calibration_report(self, table: str, field: str, query: str, labels: Sequence[int]) -> dict[str, Any]: ...
    def save_scoring_params(self, name: str, params: Mapping[str, float]) -> None: ...
    def load_scoring_params(self, name: str) -> dict[str, float] | None: ...
    def load_all_scoring_params(self) -> dict[str, dict[str, float]]: ...
    def drop_scoring_params(self, name: str) -> bool: ...
    def run_cypher(self, graph: str, query: str, params: Mapping[str, Scalar] | None = None) -> SQLResult: ...
    def create_graph(self, name: str) -> None: ...
    def drop_graph(self, name: str) -> None: ...
    def list_graphs(self) -> list[str]: ...
    def list_path_indexes(self) -> list[str]: ...
    def table_names(self) -> list[str]: ...
    def list_views(self) -> list[str]: ...
    def list_schemas(self) -> list[str]: ...
    def list_sequences(self) -> list[str]: ...
    def list_named_analyzers(self) -> list[str]: ...
    def list_foreign_servers(self) -> list[str]: ...
    def list_foreign_tables(self) -> list[str]: ...
    def take_sql_notices(self) -> list[SQLNotice]: ...
    def sql_function_depth_limit(self) -> int: ...
    def set_sql_function_depth_limit(self, limit: int) -> None: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...

def open(path: str | Path) -> Engine: ...
def open_encrypted(path: str | Path, key: str) -> Engine: ...
def open_auto(path: str | Path, key: str | None = None) -> Engine: ...
def detect_database_file(path: str | Path) -> str: ...
def open_compressed(
    path: str | Path,
    codec: str = "zstd",
    page_size: int | None = None,
    chunk_pages: int | None = None,
    level: int | None = None,
) -> Engine: ...
def open_compressed_encrypted(
    path: str | Path,
    key: str,
    codec: str = "zstd",
    page_size: int | None = None,
    chunk_pages: int | None = None,
    level: int | None = None,
) -> Engine: ...
def scalar(value: Scalar) -> SQLParam: ...
def vector(values: Sequence[float]) -> SQLParam: ...
def tensor(values: Sequence[Sequence[float]]) -> SQLParam: ...
def migrate_python_db(source: str | Path, destination: str | Path) -> dict[str, Any]: ...

__version__: str

TableRows = Sequence[Sequence[Scalar]] | Sequence[Mapping[str, Scalar]]
TableResult = tuple[Sequence[str], TableRows] | Mapping[str, Any] | Sequence[Mapping[str, Scalar]]

class AggregateState(Protocol):
    def observe(self, *args: Scalar) -> object: ...
    def finish(self) -> Scalar: ...
