#
# Unified Query Algebra
#
# Copyright (c) 2023-2026 Cognica, Inc.
#

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable, Mapping, Protocol, Sequence

Scalar = None | bool | int | float | str | bytes | list["Scalar"] | dict[str, "Scalar"]

class SQLParam:
    @staticmethod
    def scalar(value: Scalar) -> SQLParam: ...
    @staticmethod
    def vector(values: Sequence[float]) -> SQLParam: ...
    @staticmethod
    def tensor(values: Sequence[Sequence[float]]) -> SQLParam: ...

class SQLResult:
    @property
    def columns(self) -> list[str]: ...
    @property
    def rows(self) -> list[dict[str, Scalar]]: ...
    @property
    def affected_rows(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...

class Engine:
    def __init__(self) -> None: ...
    @staticmethod
    def open(path: str | Path) -> Engine: ...
    @staticmethod
    def open_encrypted(path: str | Path, key: str) -> Engine: ...
    @staticmethod
    def open_auto(path: str | Path, key: str | None = None) -> Engine: ...
    @staticmethod
    def detect_database_file(path: str | Path) -> str: ...
    @staticmethod
    def open_compressed(
        path: str | Path,
        codec: str = "zstd",
        page_size: int | None = None,
        chunk_pages: int | None = None,
        level: int | None = None,
    ) -> Engine: ...
    @staticmethod
    def open_compressed_encrypted(
        path: str | Path,
        key: str,
        codec: str = "zstd",
        page_size: int | None = None,
        chunk_pages: int | None = None,
        level: int | None = None,
    ) -> Engine: ...
    def sql(self, query: str, params: Sequence[Scalar | SQLParam] | None = None) -> SQLResult: ...
    def execute(self, query: str, params: Sequence[Scalar | SQLParam] | None = None) -> SQLResult: ...
    def sql_batch(self, statements: Sequence[tuple[str, Sequence[Scalar | SQLParam]]]) -> list[SQLResult]: ...
    def register_scalar_function(self, name: str, callable: Callable[..., Scalar]) -> None: ...
    def register_table_function(self, name: str, callable: Callable[..., TableResult]) -> None: ...
    def register_aggregate_function(self, name: str, factory: Callable[[], AggregateState]) -> None: ...
    def create_default_table(self, name: str, fts_fields: Sequence[str]) -> None: ...
    def create_vector_field(self, table: str, field: str, dimensions: int) -> bool: ...
    def add_document(self, table: str, doc_id: int, document: Mapping[str, Scalar]) -> None: ...
    def add_document_with_vectors(
        self,
        table: str,
        doc_id: int,
        document: Mapping[str, Scalar],
        vectors: Mapping[str, Sequence[float] | Sequence[Sequence[float]]],
    ) -> None: ...
    def add_vector(self, table: str, doc_id: int, field: str, vector: Sequence[float]) -> bool: ...
    def add_vector_values(self, table: str, doc_id: int, field: str, vectors: Sequence[Sequence[float]]) -> bool: ...
    def get_document(self, table: str, doc_id: int) -> dict[str, Scalar] | None: ...
    def delete_document(self, table: str, doc_id: int) -> None: ...
    def document_count(self, table: str) -> int: ...
    def search(self, table: str, field: str, query: str, top_k: int = 10, scoring: str = "bm25") -> list[dict[str, float | int]]: ...
    def knn_search(self, table: str, field: str, vector: Sequence[float], top_k: int = 10) -> list[dict[str, float | int]]: ...
    def vector_similarity_search(self, table: str, field: str, vector: Sequence[float], threshold: float) -> list[dict[str, float | int]]: ...
    def hybrid_search(
        self,
        table: str,
        text_field: str,
        text_query: str,
        vector_field: str,
        query_vector: Sequence[float],
        top_k: int = 10,
        knn_pool: int | None = None,
    ) -> list[dict[str, float | int]]: ...
    def robust_hybrid_search(
        self,
        table: str,
        text_field: str,
        text_query: str,
        vector_field: str,
        query_vector: Sequence[float],
        top_k: int = 10,
        knn_pool: int | None = None,
        alpha: float = 0.5,
    ) -> list[dict[str, float | int]]: ...
    def estimate_scoring_params(
        self,
        table: str,
        field: str,
        n_samples: int = 50,
        tokens_per_query: int = 5,
        seed: int = 42,
    ) -> dict[str, float]: ...
    def learn_scoring_params(self, table: str, field: str, query: str, labels: Sequence[int]) -> dict[str, float]: ...
    def update_scoring_params(self, table: str, field: str, score: float, label: int) -> None: ...
    def calibration_report(self, table: str, field: str, query: str, labels: Sequence[int]) -> dict[str, Any]: ...
    def save_scoring_params(self, name: str, params: Mapping[str, float]) -> None: ...
    def load_scoring_params(self, name: str) -> dict[str, float] | None: ...
    def load_all_scoring_params(self) -> dict[str, dict[str, float]]: ...
    def drop_scoring_params(self, name: str) -> bool: ...
    def run_cypher(self, graph: str, query: str, params: Mapping[str, Scalar] | None = None) -> SQLResult: ...
    def create_graph(self, name: str) -> None: ...
    def drop_graph(self, name: str) -> None: ...
    def list_graphs(self) -> list[str]: ...
    def list_path_indexes(self) -> list[str]: ...
    def table_names(self) -> list[str]: ...
    def list_views(self) -> list[str]: ...
    def list_schemas(self) -> list[str]: ...
    def list_sequences(self) -> list[str]: ...
    def list_named_analyzers(self) -> list[str]: ...
    def list_foreign_servers(self) -> list[str]: ...
    def list_foreign_tables(self) -> list[str]: ...
    def take_sql_notices(self) -> list[tuple[str, str]]: ...
    def sql_function_depth_limit(self) -> int: ...
    def set_sql_function_depth_limit(self, limit: int) -> None: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...

def open(path: str | Path) -> Engine: ...
def open_encrypted(path: str | Path, key: str) -> Engine: ...
def open_auto(path: str | Path, key: str | None = None) -> Engine: ...
def detect_database_file(path: str | Path) -> str: ...
def open_compressed(
    path: str | Path,
    codec: str = "zstd",
    page_size: int | None = None,
    chunk_pages: int | None = None,
    level: int | None = None,
) -> Engine: ...
def open_compressed_encrypted(
    path: str | Path,
    key: str,
    codec: str = "zstd",
    page_size: int | None = None,
    chunk_pages: int | None = None,
    level: int | None = None,
) -> Engine: ...
def scalar(value: Scalar) -> SQLParam: ...
def vector(values: Sequence[float]) -> SQLParam: ...
def tensor(values: Sequence[Sequence[float]]) -> SQLParam: ...
def migrate_python_db(source: str | Path, destination: str | Path) -> dict[str, Any]: ...

__version__: str

TableRows = Sequence[Sequence[Scalar]] | Sequence[Mapping[str, Scalar]]
TableResult = tuple[Sequence[str], TableRows] | Mapping[str, Any] | Sequence[Mapping[str, Scalar]]

class AggregateState(Protocol):
    def observe(self, *args: Scalar) -> object: ...
    def finish(self) -> Scalar: ...
