//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! Column and primary-key mappings for the native catalog format. Owner names are retained in row payloads and excluded from object-scoped record identities.

use super::{invalid, NativeRecordFamily};
use rusqlite::types::ValueRef;
use uqa_storage::mvcc::VersionResult;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NativeColumnType {
    Integer,
    Real,
    Text,
    Blob,
    /// TEXT column names and BLOB catalog-index identities occupy distinct namespaces in the same physical column.
    TextOrBlob,
}

impl NativeColumnType {
    pub(super) fn declaration(self) -> &'static str {
        match self {
            Self::Integer => "INTEGER",
            Self::Real => "REAL",
            Self::Text | Self::TextOrBlob => "TEXT",
            Self::Blob => "BLOB",
        }
    }

    pub(super) fn accepts(self, value: ValueRef<'_>) -> bool {
        matches!(
            (self, value),
            (Self::Integer, ValueRef::Integer(_))
                | (Self::Real, ValueRef::Real(_))
                | (Self::Text | Self::TextOrBlob, ValueRef::Text(_))
                | (Self::Blob | Self::TextOrBlob, ValueRef::Blob(_))
        )
    }
}

#[derive(Debug)]
pub struct NativeRecordLayout {
    pub family: NativeRecordFamily,
    pub table: &'static str,
    pub columns: &'static [&'static str],
    pub column_types: &'static [NativeColumnType],
    pub nullable: &'static [bool],
    pub primary_key: &'static [usize],
    pub identity_columns: &'static [usize],
    pub object_owned: bool,
}

use NativeColumnType::{Blob, Integer, Real, Text, TextOrBlob};

pub(super) const LAYOUTS: &[NativeRecordLayout] = &[
    NativeRecordLayout {
        family: NativeRecordFamily::Analyzers,
        table: "_analyzers",
        columns: &["name", "config_json", "descriptor_json"],
        column_types: &[Text, Text, Text],
        nullable: &[true, false, true],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::BtreeIndexEntries,
        table: "_btree_index_entries",
        columns: &["table_name", "field", "doc_id", "value_json"],
        column_types: &[Text, TextOrBlob, Integer, Text],
        nullable: &[false, false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::BtreeIndexRepairs,
        table: "_btree_index_repairs",
        columns: &["table_name", "field"],
        column_types: &[Text, TextOrBlob],
        nullable: &[false, false],
        primary_key: &[0, 1],
        identity_columns: &[1],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::BtreeIndexes,
        table: "_btree_indexes",
        columns: &["table_name", "field"],
        column_types: &[Text, TextOrBlob],
        nullable: &[false, false],
        primary_key: &[0, 1],
        identity_columns: &[1],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::CacheRevisions,
        table: "_cache_revisions",
        columns: &["kind", "name", "generation"],
        column_types: &[Text, Text, Integer],
        nullable: &[false, false, false],
        primary_key: &[0, 1],
        identity_columns: &[0, 1],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::CatalogIndexes,
        table: "_catalog_indexes",
        columns: &[
            "schema_name",
            "relation_name",
            "kind",
            "index_type",
            "table_schema_name",
            "table_relation_name",
            "columns",
            "parameters",
            "definition",
        ],
        column_types: &[Text, Text, Text, Text, Text, Text, Text, Text, Text],
        nullable: &[false, false, false, false, false, false, false, false, true],
        primary_key: &[0, 1],
        identity_columns: &[0, 1],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::ColumnStats,
        table: "_column_stats",
        columns: &[
            "table_name",
            "column_name",
            "distinct_count",
            "null_count",
            "min_value",
            "max_value",
            "row_count",
            "histogram",
            "mcv_values",
            "mcv_frequencies",
        ],
        column_types: &[
            Text, Text, Integer, Integer, Text, Text, Integer, Text, Text, Text,
        ],
        nullable: &[
            false, false, false, false, true, true, false, false, false, false,
        ],
        primary_key: &[0, 1],
        identity_columns: &[1],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::DocLengths,
        table: "_doc_lengths",
        columns: &["table_name", "doc_id", "field", "length"],
        column_types: &[Text, Integer, Text, Integer],
        nullable: &[false, false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::DocumentBlobs,
        table: "_document_blobs",
        columns: &["table_name", "doc_id", "field_name", "bytes"],
        column_types: &[Text, Integer, Text, Blob],
        nullable: &[false, false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::Documents,
        table: "_documents",
        columns: &["table_name", "doc_id", "body", "tuple_xmin"],
        column_types: &[Text, Integer, Text, Integer],
        nullable: &[false, false, false, true],
        primary_key: &[0, 1],
        identity_columns: &[1],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::FieldStats,
        table: "_field_stats",
        columns: &["table_name", "field", "total_length"],
        column_types: &[Text, Text, Integer],
        nullable: &[false, false, false],
        primary_key: &[0, 1],
        identity_columns: &[1],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::ForeignServers,
        table: "_foreign_servers",
        columns: &["name", "fdw_type", "options"],
        column_types: &[Text, Text, Text],
        nullable: &[true, false, false],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::ForeignTables,
        table: "_foreign_tables",
        columns: &[
            "schema_name",
            "relation_name",
            "kind",
            "server_name",
            "columns_json",
            "options",
            "role_owner",
            "acl_json",
            "column_acls_json",
        ],
        column_types: &[Text, Text, Text, Text, Text, Text, Text, Text, Text],
        nullable: &[false, false, false, false, false, false, false, true, false],
        primary_key: &[0, 1],
        identity_columns: &[0, 1],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::GraphEdges,
        table: "_graph_edges",
        columns: &[
            "edge_id",
            "source_id",
            "target_id",
            "label",
            "properties_json",
        ],
        column_types: &[Integer, Integer, Integer, Text, Text],
        nullable: &[true, false, false, false, false],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::GraphMembership,
        table: "_graph_membership",
        columns: &["entity_type", "entity_id", "graph_name"],
        column_types: &[Text, Integer, Text],
        nullable: &[false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[0, 1, 2],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::GraphPathIndexState,
        table: "_graph_path_index_state",
        columns: &["index_key", "graph_name", "definition_json", "valid"],
        column_types: &[Text, Text, Text, Integer],
        nullable: &[true, false, false, false],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::GraphPathPairs,
        table: "_graph_path_pairs",
        columns: &["index_key", "sequence_key", "source_id", "target_id"],
        column_types: &[Text, Text, Integer, Integer],
        nullable: &[false, false, false, false],
        primary_key: &[0, 1, 2, 3],
        identity_columns: &[0, 1, 2, 3],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::GraphVertices,
        table: "_graph_vertices",
        columns: &["vertex_id", "label", "properties_json"],
        column_types: &[Integer, Text, Text],
        nullable: &[true, false, false],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::HNSWEdges,
        table: "_hnsw_edges",
        columns: &[
            "table_name",
            "field",
            "source_node_id",
            "layer",
            "target_node_id",
        ],
        column_types: &[Text, Text, Integer, Integer, Integer],
        nullable: &[false, false, false, false, false],
        primary_key: &[0, 1, 2, 3, 4],
        identity_columns: &[1, 2, 3, 4],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::HNSWIndexes,
        table: "_hnsw_indexes",
        columns: &[
            "table_name",
            "field",
            "dimensions",
            "m",
            "ef_construction",
            "ef_search",
            "rebuild_threshold",
            "seed",
            "entry_node_id",
            "max_level",
            "next_node_id",
            "live_count",
            "deleted_count",
            "revision",
            "format_version",
        ],
        column_types: &[
            Text, Text, Integer, Integer, Integer, Integer, Integer, Text, Integer, Integer,
            Integer, Integer, Integer, Integer, Integer,
        ],
        nullable: &[
            false, false, false, false, false, false, false, false, true, false, false, false,
            false, false, false,
        ],
        primary_key: &[0, 1],
        identity_columns: &[1],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::HNSWNodes,
        table: "_hnsw_nodes",
        columns: &[
            "table_name",
            "field",
            "node_id",
            "doc_id",
            "vector_ordinal",
            "level",
            "deleted",
            "vector",
        ],
        column_types: &[
            Text, Text, Integer, Integer, Integer, Integer, Integer, Blob,
        ],
        nullable: &[false, false, false, false, false, false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::IVFAssignments,
        table: "_ivf_assignments",
        columns: &[
            "table_name",
            "field",
            "doc_id",
            "vector_ordinal",
            "centroid_id",
        ],
        column_types: &[Text, Text, Integer, Integer, Integer],
        nullable: &[false, false, false, false, false],
        primary_key: &[0, 1, 2, 3],
        identity_columns: &[1, 2, 3],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::IVFCentroids,
        table: "_ivf_centroids",
        columns: &["table_name", "field", "centroid_id", "vector"],
        column_types: &[Text, Text, Integer, Blob],
        nullable: &[false, false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::IVFIndexes,
        table: "_ivf_indexes",
        columns: &[
            "table_name",
            "field",
            "dimensions",
            "nlist",
            "nprobe",
            "train_threshold",
            "state",
            "trained_size",
            "deletes_since_train",
            "vector_count",
        ],
        column_types: &[
            Text, Text, Integer, Integer, Integer, Integer, Text, Integer, Integer, Integer,
        ],
        nullable: &[
            false, false, false, false, false, false, false, false, false, false,
        ],
        primary_key: &[0, 1],
        identity_columns: &[1],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::Metadata,
        table: "_metadata",
        columns: &["key", "value"],
        column_types: &[Text, Text],
        nullable: &[true, false],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::Models,
        table: "_models",
        columns: &["name", "body"],
        column_types: &[Text, Text],
        nullable: &[true, false],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::NamedGraphs,
        table: "_named_graphs",
        columns: &["name"],
        column_types: &[Text],
        nullable: &[true],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::OccurrenceClusters,
        table: "_occurrence_clusters",
        columns: &[
            "table_name",
            "field",
            "term",
            "cluster_id",
            "posting_count",
            "score_blob",
            "positions_blob",
        ],
        column_types: &[Text, Text, Blob, Integer, Integer, Blob, Blob],
        nullable: &[false, false, false, false, false, false, false],
        primary_key: &[0, 1, 2, 3],
        identity_columns: &[1, 2, 3],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::OccurrenceDocuments,
        table: "_occurrence_documents",
        columns: &[
            "table_name",
            "doc_id",
            "field",
            "terms_blob",
            "metadata_blob",
        ],
        column_types: &[Text, Integer, Text, Blob, Blob],
        nullable: &[false, false, false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::OccurrenceFields,
        table: "_occurrence_fields",
        columns: &[
            "table_name",
            "field",
            "revision",
            "doc_count",
            "total_length",
        ],
        column_types: &[Text, Text, Blob, Integer, Integer],
        nullable: &[false, false, false, false, false],
        primary_key: &[0, 1],
        identity_columns: &[1],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::OccurrenceFormats,
        table: "_occurrence_formats",
        columns: &["table_name", "format"],
        column_types: &[Text, Text],
        nullable: &[false, false],
        primary_key: &[0],
        identity_columns: &[],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::OccurrenceLengths,
        table: "_occurrence_lengths",
        columns: &["table_name", "doc_id", "field", "length"],
        column_types: &[Text, Integer, Text, Integer],
        nullable: &[false, false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::PathIndexes,
        table: "_path_indexes",
        columns: &["graph_name", "label_sequences"],
        column_types: &[Text, Text],
        nullable: &[true, false],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::PostingClusters,
        table: "_posting_clusters",
        columns: &[
            "table_name",
            "field",
            "term",
            "cluster_id",
            "posting_count",
            "score_blob",
            "positions_blob",
        ],
        column_types: &[Text, Text, Text, Integer, Integer, Blob, Blob],
        nullable: &[false, false, false, false, false, false, false],
        primary_key: &[0, 1, 2, 3],
        identity_columns: &[1, 2, 3],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::PostingDocuments,
        table: "_posting_documents",
        columns: &["table_name", "doc_id", "field", "terms_blob"],
        column_types: &[Text, Integer, Text, Blob],
        nullable: &[false, false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::Relations,
        table: "_relations",
        columns: &["schema_name", "relation_name", "kind"],
        column_types: &[Text, Text, Text],
        nullable: &[false, false, false],
        primary_key: &[0, 1],
        identity_columns: &[0, 1],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::Schemas,
        table: "_schemas",
        columns: &["name", "role_owner", "acl_json"],
        column_types: &[Text, Text, Text],
        nullable: &[true, false, true],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::ScoringParams,
        table: "_scoring_params",
        columns: &["name", "params"],
        column_types: &[Text, Text],
        nullable: &[true, false],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::Sequences,
        table: "_sequences",
        columns: &[
            "schema_name",
            "relation_name",
            "kind",
            "start",
            "increment",
            "current",
            "called",
            "persistence",
            "object_id",
            "data_type",
            "min_value",
            "max_value",
            "cycle",
            "cache_size",
            "definition_generation",
            "owner_table_object_id",
            "owner_column_object_id",
            "owner_dependency",
            "role_owner",
            "acl_json",
            "log_count",
        ],
        column_types: &[
            Text, Text, Text, Integer, Integer, Integer, Integer, Text, Blob, Text, Integer,
            Integer, Integer, Integer, Blob, Blob, Blob, Text, Text, Text, Integer,
        ],
        nullable: &[
            false, false, false, false, false, false, false, false, false, false, false, false,
            false, false, false, true, true, true, false, true, false,
        ],
        primary_key: &[0, 1],
        identity_columns: &[],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::TableFieldAnalyzers,
        table: "_table_field_analyzers",
        columns: &[
            "table_name",
            "field",
            "phase",
            "analyzer_name",
            "binding_json",
        ],
        column_types: &[Text, Text, Text, Text, Text],
        nullable: &[false, false, false, false, true],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::Tables,
        table: "_tables",
        columns: &[
            "schema_name",
            "relation_name",
            "kind",
            "analyzer",
            "fts_fields",
            "vector_fields",
            "columns",
            "constraints",
            "storage_generation",
            "object_id",
            "role_owner",
            "acl_json",
            "column_acls_json",
        ],
        column_types: &[
            Text, Text, Text, Text, Text, Text, Text, Text, Blob, Blob, Text, Text, Text,
        ],
        nullable: &[
            false, false, false, false, false, false, true, false, false, false, false, true, true,
        ],
        primary_key: &[0, 1],
        identity_columns: &[],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::Vectors,
        table: "_vectors",
        columns: &["table_name", "field", "doc_id", "vector_ordinal", "vector"],
        column_types: &[Text, Text, Integer, Integer, Blob],
        nullable: &[false, false, false, false, false],
        primary_key: &[0, 1, 2, 3],
        identity_columns: &[1, 2, 3],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::Views,
        table: "_views",
        columns: &[
            "schema_name",
            "relation_name",
            "kind",
            "definition_json",
            "role_owner",
            "acl_json",
            "column_acls_json",
        ],
        column_types: &[Text, Text, Text, Text, Text, Text, Text],
        nullable: &[false, false, false, false, false, true, true],
        primary_key: &[0, 1],
        identity_columns: &[0, 1],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::TableOwners,
        table: "_uqa_mvcc_native_owners",
        columns: &["name", "object_id", "generation", "catalog_owned"],
        column_types: &[Text, Blob, Blob, Integer],
        nullable: &[false, false, false, false],
        primary_key: &[0],
        identity_columns: &[0],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::GraphLookups,
        table: "_uqa_mvcc_native_graph_lookup",
        columns: &[
            "kind",
            "text_key",
            "integer_key",
            "entity_type",
            "entity_id",
        ],
        column_types: &[Text, Text, Integer, Text, Integer],
        nullable: &[false, false, false, false, false],
        primary_key: &[0, 1, 2, 3, 4],
        identity_columns: &[0, 1, 2, 3, 4],
        object_owned: false,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::OccurrenceSkips,
        table: "_occurrence_skips",
        columns: &["table_name", "field", "term", "skip_doc_id", "skip_offset"],
        column_types: &[Text, Text, Blob, Integer, Integer],
        nullable: &[false, false, false, false, false],
        primary_key: &[0, 1, 2, 3],
        identity_columns: &[1, 2, 3],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::OccurrenceBlockMax,
        table: "_occurrence_block_max",
        columns: &[
            "table_name",
            "field",
            "term",
            "block_idx",
            "max_score",
            "scorer_fingerprint",
        ],
        column_types: &[Text, Text, Blob, Integer, Real, Text],
        nullable: &[false, false, false, false, false, false],
        primary_key: &[0, 1, 2, 3],
        identity_columns: &[1, 2, 3],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::OccurrenceGuards,
        table: "_uqa_mvcc_native_occurrence_guards",
        columns: &["table_name", "document_id"],
        column_types: &[Text, Integer],
        nullable: &[false, false],
        primary_key: &[0, 1],
        identity_columns: &[1],
        object_owned: true,
    },
    NativeRecordLayout {
        family: NativeRecordFamily::IVFGuards,
        table: "_uqa_mvcc_native_ivf_guards",
        columns: &["table_name", "field", "document_id"],
        column_types: &[Text, Text, Integer],
        nullable: &[false, false, false],
        primary_key: &[0, 1, 2],
        identity_columns: &[1, 2],
        object_owned: true,
    },
];

impl NativeRecordLayout {
    pub fn validate_values(&self, values: &[ValueRef<'_>]) -> VersionResult<()> {
        if values.len() != self.columns.len() {
            return Err(invalid("native row column count does not match its layout"));
        }
        for ((value, expected), nullable) in values.iter().zip(self.column_types).zip(self.nullable)
        {
            let matches = match value {
                ValueRef::Null => *nullable,
                value => expected.accepts(*value),
            };
            if !matches {
                return Err(invalid(
                    "native row storage class does not match its layout",
                ));
            }
        }
        Ok(())
    }
}
