//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

use super::TemporalTimeZone;

enum Abbreviation {
    Fixed(i32),
    Named(&'static str),
}

pub(super) fn lookup(name: &str) -> Option<TemporalTimeZone> {
    let index = DEFAULT
        .binary_search_by(|(candidate, _)| {
            candidate
                .bytes()
                .cmp(name.bytes().map(|byte| byte.to_ascii_uppercase()))
        })
        .ok()?;
    match DEFAULT[index].1 {
        Abbreviation::Fixed(offset) => TemporalTimeZone::fixed(offset),
        Abbreviation::Named(name) => TemporalTimeZone::named(name),
    }
}

// PostgreSQL 18 src/timezone/tznames/Default; dynamic abbreviations keep their
// referenced zone, as DecodeTimezoneNameToTz does. The trailing daylight flag
// on fixed abbreviations does not alter their offset.
const DEFAULT: &[(&str, Abbreviation)] = &[
    ("ACDT", Abbreviation::Fixed(37800)),
    ("ACSST", Abbreviation::Fixed(37800)),
    ("ACST", Abbreviation::Fixed(34200)),
    ("ACT", Abbreviation::Fixed(-18000)),
    ("ACWST", Abbreviation::Fixed(31500)),
    ("ADT", Abbreviation::Fixed(-10800)),
    ("AEDT", Abbreviation::Fixed(39600)),
    ("AESST", Abbreviation::Fixed(39600)),
    ("AEST", Abbreviation::Fixed(36000)),
    ("AFT", Abbreviation::Fixed(16200)),
    ("AKDT", Abbreviation::Fixed(-28800)),
    ("AKST", Abbreviation::Fixed(-32400)),
    ("ALMST", Abbreviation::Fixed(25200)),
    ("ALMT", Abbreviation::Fixed(21600)),
    ("AMST", Abbreviation::Named("Asia/Yerevan")),
    ("AMT", Abbreviation::Fixed(-14400)),
    ("ANAST", Abbreviation::Named("Asia/Anadyr")),
    ("ANAT", Abbreviation::Named("Asia/Anadyr")),
    (
        "ARST",
        Abbreviation::Named("America/Argentina/Buenos_Aires"),
    ),
    ("ART", Abbreviation::Named("America/Argentina/Buenos_Aires")),
    ("AST", Abbreviation::Fixed(-14400)),
    ("AWSST", Abbreviation::Fixed(32400)),
    ("AWST", Abbreviation::Fixed(28800)),
    ("AZOST", Abbreviation::Fixed(0)),
    ("AZOT", Abbreviation::Fixed(-3600)),
    ("AZST", Abbreviation::Named("Asia/Baku")),
    ("AZT", Abbreviation::Named("Asia/Baku")),
    ("BDST", Abbreviation::Fixed(7200)),
    ("BDT", Abbreviation::Fixed(21600)),
    ("BNT", Abbreviation::Fixed(28800)),
    ("BORT", Abbreviation::Fixed(28800)),
    ("BOT", Abbreviation::Fixed(-14400)),
    ("BRA", Abbreviation::Fixed(-10800)),
    ("BRST", Abbreviation::Fixed(-7200)),
    ("BRT", Abbreviation::Fixed(-10800)),
    ("BST", Abbreviation::Fixed(3600)),
    ("BTT", Abbreviation::Fixed(21600)),
    ("CADT", Abbreviation::Fixed(37800)),
    ("CAST", Abbreviation::Fixed(34200)),
    ("CCT", Abbreviation::Fixed(28800)),
    ("CDT", Abbreviation::Fixed(-18000)),
    ("CEST", Abbreviation::Fixed(7200)),
    ("CET", Abbreviation::Fixed(3600)),
    ("CETDST", Abbreviation::Fixed(7200)),
    ("CHADT", Abbreviation::Fixed(49500)),
    ("CHAST", Abbreviation::Fixed(45900)),
    ("CHUT", Abbreviation::Fixed(36000)),
    ("CKT", Abbreviation::Named("Pacific/Rarotonga")),
    ("CLST", Abbreviation::Fixed(-10800)),
    ("CLT", Abbreviation::Named("America/Santiago")),
    ("COT", Abbreviation::Fixed(-18000)),
    ("CST", Abbreviation::Fixed(-21600)),
    ("CXT", Abbreviation::Fixed(25200)),
    ("DAVT", Abbreviation::Named("Antarctica/Davis")),
    ("DDUT", Abbreviation::Fixed(36000)),
    ("EASST", Abbreviation::Named("Pacific/Easter")),
    ("EAST", Abbreviation::Named("Pacific/Easter")),
    ("EAT", Abbreviation::Fixed(10800)),
    ("EDT", Abbreviation::Fixed(-14400)),
    ("EEST", Abbreviation::Fixed(10800)),
    ("EET", Abbreviation::Fixed(7200)),
    ("EETDST", Abbreviation::Fixed(10800)),
    ("EGST", Abbreviation::Fixed(0)),
    ("EGT", Abbreviation::Fixed(-3600)),
    ("EST", Abbreviation::Fixed(-18000)),
    ("FET", Abbreviation::Fixed(10800)),
    ("FJST", Abbreviation::Fixed(46800)),
    ("FJT", Abbreviation::Fixed(43200)),
    ("FKST", Abbreviation::Named("Atlantic/Stanley")),
    ("FKT", Abbreviation::Named("Atlantic/Stanley")),
    ("FNST", Abbreviation::Fixed(-3600)),
    ("FNT", Abbreviation::Fixed(-7200)),
    ("GALT", Abbreviation::Fixed(-21600)),
    ("GAMT", Abbreviation::Fixed(-32400)),
    ("GEST", Abbreviation::Named("Asia/Tbilisi")),
    ("GET", Abbreviation::Named("Asia/Tbilisi")),
    ("GFT", Abbreviation::Fixed(-10800)),
    ("GILT", Abbreviation::Fixed(43200)),
    ("GMT", Abbreviation::Fixed(0)),
    ("GYT", Abbreviation::Named("America/Guyana")),
    ("HKT", Abbreviation::Fixed(28800)),
    ("HST", Abbreviation::Fixed(-36000)),
    ("ICT", Abbreviation::Fixed(25200)),
    ("IDT", Abbreviation::Fixed(10800)),
    ("IOT", Abbreviation::Named("Indian/Chagos")),
    ("IRKST", Abbreviation::Named("Asia/Irkutsk")),
    ("IRKT", Abbreviation::Named("Asia/Irkutsk")),
    ("IRT", Abbreviation::Fixed(12600)),
    ("IST", Abbreviation::Fixed(7200)),
    ("JAYT", Abbreviation::Fixed(32400)),
    ("JST", Abbreviation::Fixed(32400)),
    ("KDT", Abbreviation::Fixed(36000)),
    ("KGST", Abbreviation::Fixed(21600)),
    ("KGT", Abbreviation::Named("Asia/Bishkek")),
    ("KOST", Abbreviation::Named("Pacific/Kosrae")),
    ("KRAST", Abbreviation::Named("Asia/Krasnoyarsk")),
    ("KRAT", Abbreviation::Named("Asia/Krasnoyarsk")),
    ("KST", Abbreviation::Fixed(32400)),
    ("LHDT", Abbreviation::Named("Australia/Lord_Howe")),
    ("LHST", Abbreviation::Fixed(37800)),
    ("LIGT", Abbreviation::Fixed(36000)),
    ("LINT", Abbreviation::Named("Pacific/Kiritimati")),
    ("LKT", Abbreviation::Named("Asia/Colombo")),
    ("MAGST", Abbreviation::Named("Asia/Magadan")),
    ("MAGT", Abbreviation::Named("Asia/Magadan")),
    ("MART", Abbreviation::Fixed(-34200)),
    ("MAWT", Abbreviation::Named("Antarctica/Mawson")),
    ("MDT", Abbreviation::Fixed(-21600)),
    ("MEST", Abbreviation::Fixed(7200)),
    ("MESZ", Abbreviation::Fixed(7200)),
    ("MET", Abbreviation::Fixed(3600)),
    ("METDST", Abbreviation::Fixed(7200)),
    ("MEZ", Abbreviation::Fixed(3600)),
    ("MHT", Abbreviation::Fixed(43200)),
    ("MMT", Abbreviation::Fixed(23400)),
    ("MPT", Abbreviation::Fixed(36000)),
    ("MSD", Abbreviation::Fixed(14400)),
    ("MSK", Abbreviation::Named("Europe/Moscow")),
    ("MST", Abbreviation::Fixed(-25200)),
    ("MUST", Abbreviation::Fixed(18000)),
    ("MUT", Abbreviation::Fixed(14400)),
    ("MVT", Abbreviation::Fixed(18000)),
    ("MYT", Abbreviation::Fixed(28800)),
    ("NDT", Abbreviation::Fixed(-9000)),
    ("NFT", Abbreviation::Fixed(-12600)),
    ("NOVST", Abbreviation::Named("Asia/Novosibirsk")),
    ("NOVT", Abbreviation::Named("Asia/Novosibirsk")),
    ("NPT", Abbreviation::Fixed(20700)),
    ("NST", Abbreviation::Fixed(-12600)),
    ("NUT", Abbreviation::Named("Pacific/Niue")),
    ("NZDT", Abbreviation::Fixed(46800)),
    ("NZST", Abbreviation::Fixed(43200)),
    ("NZT", Abbreviation::Fixed(43200)),
    ("OMSST", Abbreviation::Named("Asia/Omsk")),
    ("OMST", Abbreviation::Named("Asia/Omsk")),
    ("PDT", Abbreviation::Fixed(-25200)),
    ("PET", Abbreviation::Fixed(-18000)),
    ("PETST", Abbreviation::Named("Asia/Kamchatka")),
    ("PETT", Abbreviation::Named("Asia/Kamchatka")),
    ("PGT", Abbreviation::Fixed(36000)),
    ("PHT", Abbreviation::Fixed(28800)),
    ("PKST", Abbreviation::Fixed(21600)),
    ("PKT", Abbreviation::Fixed(18000)),
    ("PMDT", Abbreviation::Fixed(-7200)),
    ("PMST", Abbreviation::Fixed(-10800)),
    ("PONT", Abbreviation::Fixed(39600)),
    ("PST", Abbreviation::Fixed(-28800)),
    ("PWT", Abbreviation::Fixed(32400)),
    ("PYST", Abbreviation::Fixed(-10800)),
    ("PYT", Abbreviation::Named("America/Asuncion")),
    ("RET", Abbreviation::Fixed(14400)),
    ("SADT", Abbreviation::Fixed(37800)),
    ("SAST", Abbreviation::Fixed(7200)),
    ("SCT", Abbreviation::Fixed(14400)),
    ("SGT", Abbreviation::Named("Asia/Singapore")),
    ("TAHT", Abbreviation::Fixed(-36000)),
    ("TFT", Abbreviation::Fixed(18000)),
    ("TJT", Abbreviation::Fixed(18000)),
    ("TKT", Abbreviation::Named("Pacific/Fakaofo")),
    ("TMT", Abbreviation::Named("Asia/Ashgabat")),
    ("TOT", Abbreviation::Fixed(46800)),
    ("TRUT", Abbreviation::Fixed(36000)),
    ("TVT", Abbreviation::Fixed(43200)),
    ("UCT", Abbreviation::Fixed(0)),
    ("ULAST", Abbreviation::Fixed(32400)),
    ("ULAT", Abbreviation::Named("Asia/Ulaanbaatar")),
    ("UT", Abbreviation::Fixed(0)),
    ("UTC", Abbreviation::Fixed(0)),
    ("UYST", Abbreviation::Fixed(-7200)),
    ("UYT", Abbreviation::Fixed(-10800)),
    ("UZST", Abbreviation::Fixed(21600)),
    ("UZT", Abbreviation::Fixed(18000)),
    ("VET", Abbreviation::Named("America/Caracas")),
    ("VLAST", Abbreviation::Named("Asia/Vladivostok")),
    ("VLAT", Abbreviation::Named("Asia/Vladivostok")),
    ("VOLT", Abbreviation::Named("Europe/Volgograd")),
    ("VUT", Abbreviation::Fixed(39600)),
    ("WADT", Abbreviation::Fixed(28800)),
    ("WAKT", Abbreviation::Fixed(43200)),
    ("WAST", Abbreviation::Fixed(25200)),
    ("WAT", Abbreviation::Fixed(3600)),
    ("WDT", Abbreviation::Fixed(32400)),
    ("WET", Abbreviation::Fixed(0)),
    ("WETDST", Abbreviation::Fixed(3600)),
    ("WFT", Abbreviation::Fixed(43200)),
    ("WGST", Abbreviation::Fixed(-7200)),
    ("WGT", Abbreviation::Fixed(-10800)),
    ("XJT", Abbreviation::Fixed(21600)),
    ("YAKST", Abbreviation::Named("Asia/Yakutsk")),
    ("YAKT", Abbreviation::Named("Asia/Yakutsk")),
    ("YAPT", Abbreviation::Fixed(36000)),
    ("YEKST", Abbreviation::Fixed(21600)),
    ("YEKT", Abbreviation::Named("Asia/Yekaterinburg")),
    ("Z", Abbreviation::Fixed(0)),
    ("ZULU", Abbreviation::Fixed(0)),
];
