//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! Hierarchy traversal and direct-leaf mutation regressions.

use super::exec;
use uqa_core::Value;
use uqa_engine::Engine;

#[test]
fn diamond_inheritance_scans_each_physical_descendant_once() {
    let engine = Engine::new();
    exec(&engine, "CREATE TABLE hierarchy_root (id INTEGER)");
    exec(
        &engine,
        "CREATE TABLE hierarchy_left (left_value INTEGER) INHERITS (hierarchy_root)",
    );
    exec(
        &engine,
        "CREATE TABLE hierarchy_right (right_value INTEGER) INHERITS (hierarchy_root)",
    );
    exec(
        &engine,
        "CREATE TABLE hierarchy_diamond (leaf_value INTEGER) INHERITS (hierarchy_left, hierarchy_right)",
    );
    exec(
        &engine,
        "INSERT INTO hierarchy_diamond (id, left_value, right_value, leaf_value) VALUES (1, 2, 3, 4)",
    );

    let rows = engine.sql("SELECT id FROM hierarchy_root", &[]).unwrap();
    assert_eq!(rows.rows.len(), 1);
    assert_eq!(rows.rows[0]["id"], Value::Int(1));
}

#[test]
fn point_update_cannot_bypass_a_direct_partition_bound() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE point_parent (id INTEGER PRIMARY KEY) PARTITION BY RANGE (id)",
    );
    exec(
        &engine,
        "CREATE TABLE point_leaf PARTITION OF point_parent FOR VALUES FROM (0) TO (10)",
    );
    exec(&engine, "INSERT INTO point_leaf VALUES (1)");

    let error = engine
        .sql("UPDATE point_leaf SET id = 20 WHERE id = 1", &[])
        .unwrap_err();
    assert_eq!(error.sqlstate(), Some("23514"));
    assert_eq!(
        engine.sql("SELECT id FROM point_leaf", &[]).unwrap().rows[0]["id"],
        Value::Int(1)
    );
}

#[test]
fn nested_leaf_mutations_validate_every_ancestor_partition_bound() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE nested_root (id INTEGER PRIMARY KEY, region INTEGER, bucket INTEGER) PARTITION BY RANGE (region)",
    );
    exec(
        &engine,
        "CREATE TABLE nested_low PARTITION OF nested_root FOR VALUES FROM (0) TO (100) PARTITION BY RANGE (bucket)",
    );
    exec(
        &engine,
        "CREATE TABLE nested_low_a PARTITION OF nested_low FOR VALUES FROM (0) TO (10)",
    );
    exec(
        &engine,
        "CREATE TABLE nested_high PARTITION OF nested_root FOR VALUES FROM (100) TO (200)",
    );
    exec(&engine, "INSERT INTO nested_low_a VALUES (1, 1, 1)");

    let insert_error = engine
        .sql("INSERT INTO nested_low_a VALUES (2, 150, 2)", &[])
        .unwrap_err();
    assert_eq!(insert_error.sqlstate(), Some("23514"));
    let update_error = engine
        .sql("UPDATE nested_low_a SET region = 150 WHERE id = 1", &[])
        .unwrap_err();
    assert_eq!(update_error.sqlstate(), Some("23514"));
    let row = engine
        .sql("SELECT region, bucket FROM nested_low_a WHERE id = 1", &[])
        .unwrap();
    assert_eq!(row.rows[0]["region"], Value::Int(1));
    assert_eq!(row.rows[0]["bucket"], Value::Int(1));
}

#[test]
fn generated_partition_key_routes_after_identity_allocation() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE identity_routes (id INTEGER GENERATED BY DEFAULT AS IDENTITY, note TEXT) PARTITION BY RANGE (id)",
    );
    exec(
        &engine,
        "CREATE TABLE identity_routes_low PARTITION OF identity_routes FOR VALUES FROM (0) TO (3)",
    );
    exec(
        &engine,
        "CREATE TABLE identity_routes_high PARTITION OF identity_routes FOR VALUES FROM (3) TO (10)",
    );

    let inserted = engine
        .sql(
            "INSERT INTO identity_routes (note) VALUES ('one'), ('two'), ('three') RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(inserted.rows[0]["id"], Value::Int(1));
    assert_eq!(inserted.rows[1]["id"], Value::Int(2));
    assert_eq!(inserted.rows[2]["id"], Value::Int(3));
    assert_eq!(
        engine
            .sql("SELECT count(*) AS count FROM identity_routes_low", &[])
            .unwrap()
            .rows[0]["count"],
        Value::Int(2)
    );
    assert_eq!(
        engine
            .sql("SELECT count(*) AS count FROM identity_routes_high", &[])
            .unwrap()
            .rows[0]["count"],
        Value::Int(1)
    );
}

fn seed_partition_identity_database(database: &std::path::Path) {
    let engine = Engine::open(database).unwrap();
    exec(
        &engine,
        "CREATE TABLE identity_parent (id SERIAL, bucket INTEGER, note TEXT) PARTITION BY RANGE (bucket)",
    );
    exec(
        &engine,
        "CREATE TABLE identity_low PARTITION OF identity_parent FOR VALUES FROM (0) TO (10)",
    );
    exec(
        &engine,
        "CREATE TABLE identity_high PARTITION OF identity_parent FOR VALUES FROM (10) TO (20)",
    );
    let root = engine
        .sql(
            "INSERT INTO identity_parent (bucket, note) VALUES (1, 'root') RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(root.rows[0]["id"], Value::Int(1));
    let direct = engine
        .sql(
            "INSERT INTO identity_high (bucket, note) VALUES (11, 'direct') RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(direct.rows[0]["id"], Value::Int(2));
    exec(
        &engine,
        "CREATE TABLE identity_insert_source (bucket INTEGER, note TEXT)",
    );
    exec(
        &engine,
        "INSERT INTO identity_insert_source VALUES (2, 'select-low'), (12, 'select-high')",
    );
    let selected = engine
        .sql(
            "INSERT INTO identity_parent (bucket, note) SELECT bucket, note FROM identity_insert_source ORDER BY bucket RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(selected.rows[0]["id"], Value::Int(3));
    assert_eq!(selected.rows[1]["id"], Value::Int(4));
    exec(
        &engine,
        "CREATE TABLE identity_merge_source (bucket INTEGER, note TEXT)",
    );
    exec(
        &engine,
        "INSERT INTO identity_merge_source VALUES (13, 'merge-high')",
    );
    let merged = engine
        .sql(
            "MERGE INTO identity_parent AS target USING identity_merge_source AS source ON false WHEN NOT MATCHED THEN INSERT (bucket, note) VALUES (source.bucket, source.note) RETURNING new.id AS id",
            &[],
        )
        .unwrap();
    assert_eq!(merged.rows[0]["id"], Value::Int(5));
}

fn assert_partition_identity_restart_persistence(database: &std::path::Path) {
    let reopened = Engine::open(database).unwrap();
    let inserted = reopened
        .sql(
            "INSERT INTO identity_low (bucket, note) VALUES (3, 'reopened') RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(inserted.rows[0]["id"], Value::Int(6));
    exec(&reopened, "TRUNCATE identity_low RESTART IDENTITY");
    let after_leaf_restart = reopened
        .sql(
            "INSERT INTO identity_high (bucket, note) VALUES (14, 'leaf-restart') RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(after_leaf_restart.rows[0]["id"], Value::Int(7));
    exec(&reopened, "TRUNCATE identity_parent CONTINUE IDENTITY");
    drop(reopened);

    let reopened = Engine::open(database).unwrap();
    let continued = reopened
        .sql(
            "INSERT INTO identity_high (bucket, note) VALUES (15, 'continued') RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(continued.rows[0]["id"], Value::Int(8));
    exec(&reopened, "TRUNCATE identity_parent RESTART IDENTITY");
    let restarted = reopened
        .sql(
            "INSERT INTO identity_low (bucket, note) VALUES (4, 'restarted') RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(restarted.rows[0]["id"], Value::Int(1));
    drop(reopened);

    let reopened = Engine::open(database).unwrap();
    let reopened_again = reopened
        .sql(
            "INSERT INTO identity_high (bucket, note) VALUES (16, 'reopened-again') RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(reopened_again.rows[0]["id"], Value::Int(2));
}

#[test]
fn partition_identity_allocator_is_shared_by_all_insert_paths_and_reopen() {
    let directory = tempfile::tempdir().unwrap();
    let database = directory.path().join("partition-identity.db");
    seed_partition_identity_database(&database);
    assert_partition_identity_restart_persistence(&database);
}

#[test]
fn truncate_hierarchy_honors_continue_and_restart_identity() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE truncate_parent (id SERIAL, bucket INTEGER) PARTITION BY RANGE (bucket)",
    );
    exec(
        &engine,
        "CREATE TABLE truncate_leaf PARTITION OF truncate_parent FOR VALUES FROM (0) TO (10)",
    );
    let first = engine
        .sql(
            "INSERT INTO truncate_parent (bucket) VALUES (1) RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(first.rows[0]["id"], Value::Int(1));

    exec(&engine, "TRUNCATE truncate_parent CONTINUE IDENTITY");
    let continued = engine
        .sql(
            "INSERT INTO truncate_parent (bucket) VALUES (1) RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(continued.rows[0]["id"], Value::Int(2));

    exec(&engine, "TRUNCATE truncate_parent RESTART IDENTITY");
    let restarted = engine
        .sql(
            "INSERT INTO truncate_parent (bucket) VALUES (1) RETURNING id",
            &[],
        )
        .unwrap();
    assert_eq!(restarted.rows[0]["id"], Value::Int(1));
}

#[test]
fn parent_for_update_locks_the_physical_partition_tuple() {
    let directory = tempfile::tempdir().unwrap();
    let root = Engine::open(&directory.path().join("hierarchy-row-lock.db")).unwrap();
    exec(
        &root,
        "CREATE TABLE lock_parent (id INTEGER PRIMARY KEY) PARTITION BY RANGE (id)",
    );
    exec(
        &root,
        "CREATE TABLE lock_leaf PARTITION OF lock_parent FOR VALUES FROM (0) TO (10)",
    );
    exec(&root, "INSERT INTO lock_parent VALUES (1)");
    let holder = root.new_session().unwrap();
    let waiter = root.new_session().unwrap();

    exec(&holder, "BEGIN");
    holder
        .sql("SELECT id FROM lock_parent WHERE id = 1 FOR UPDATE", &[])
        .unwrap();
    let error = waiter
        .sql(
            "SELECT id FROM lock_leaf WHERE id = 1 FOR UPDATE NOWAIT",
            &[],
        )
        .unwrap_err();
    assert_eq!(error.sqlstate(), Some("55P03"));
    exec(&holder, "ROLLBACK");
}
