//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! `PostgreSQL` text/CSV COPY over ordinary inheritance and partitions.

use super::{exec, Engine, Value};

fn copy_to_string(engine: &Engine, statement: &str) -> String {
    let mut output = Vec::new();
    engine.copy_to(statement, &mut output).unwrap();
    String::from_utf8(output).unwrap()
}

#[test]
fn ordinary_inheritance_copy_uses_named_storage_and_query_scan_semantics() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE copy_parent (id INTEGER, payload TEXT DEFAULT 'parent-default', doubled INTEGER GENERATED ALWAYS AS (id * 2) STORED, CHECK (id > 0))",
    );
    exec(
        &engine,
        "CREATE TABLE copy_child (extra TEXT DEFAULT 'child-default') INHERITS (copy_parent)",
    );

    assert_eq!(
        engine
            .copy_from("COPY copy_parent (id) FROM STDIN", b"1\n".as_slice())
            .unwrap(),
        1
    );
    assert_eq!(
        engine
            .copy_from(
                "COPY copy_child (id, extra) FROM STDIN",
                b"2\tchild\n".as_slice(),
            )
            .unwrap(),
        1
    );

    assert_eq!(
        copy_to_string(&engine, "COPY copy_parent TO STDOUT"),
        "1\tparent-default\n"
    );
    assert_eq!(
        copy_to_string(
            &engine,
            "COPY (SELECT id, payload, doubled FROM copy_parent ORDER BY id) TO STDOUT",
        ),
        "1\tparent-default\t2\n2\tparent-default\t4\n"
    );
    assert_eq!(
        copy_to_string(
            &engine,
            "COPY (SELECT id, payload, doubled FROM ONLY copy_parent ORDER BY id) TO STDOUT",
        ),
        "1\tparent-default\t2\n"
    );
    let only_syntax = engine
        .copy_to("COPY ONLY copy_parent TO STDOUT", Vec::new())
        .unwrap_err();
    assert_eq!(only_syntax.sqlstate(), Some("42601"));

    exec(&engine, "CREATE SCHEMA \"copy.schema\"");
    exec(
        &engine,
        "CREATE TABLE \"copy.schema\".\"Odd.Table\" (\"Odd Column\" INTEGER, payload TEXT DEFAULT 'quoted')",
    );
    assert_eq!(
        engine
            .copy_from(
                "COPY \"copy.schema\".\"Odd.Table\" (\"Odd Column\") FROM STDIN",
                b"7\n".as_slice(),
            )
            .unwrap(),
        1
    );
    assert_eq!(
        copy_to_string(&engine, "COPY \"copy.schema\".\"Odd.Table\" TO STDOUT",),
        "7\tquoted\n"
    );
}

fn create_range_copy_fixture(engine: &Engine) {
    exec(
        engine,
        "CREATE TABLE copy_ranges (id BIGINT GENERATED BY DEFAULT AS IDENTITY, bucket INTEGER, payload TEXT DEFAULT 'range-default', generated_value TEXT GENERATED ALWAYS AS (payload || ':' || bucket::text) STORED, CHECK (bucket >= 0)) PARTITION BY RANGE (bucket)",
    );
    exec(
        engine,
        "CREATE TABLE copy_ranges_low PARTITION OF copy_ranges FOR VALUES FROM (0) TO (10)",
    );
    exec(
        engine,
        "CREATE TABLE copy_ranges_high PARTITION OF copy_ranges FOR VALUES FROM (10) TO (20)",
    );
    exec(
        engine,
        "CREATE TABLE copy_ranges_default PARTITION OF copy_ranges DEFAULT",
    );
}

fn assert_range_copy_rows(engine: &Engine) {
    let rows = engine
        .sql(
            "SELECT id, bucket, payload, generated_value FROM copy_ranges ORDER BY id",
            &[],
        )
        .unwrap();
    assert_eq!(rows.rows.len(), 3);
    assert_eq!(rows.rows[0]["id"], Value::Int(1));
    assert_eq!(rows.rows[0]["generated_value"], Value::Str("one:1".into()));
    assert_eq!(rows.rows[1]["id"], Value::Int(2));
    assert_eq!(rows.rows[2]["id"], Value::Int(3));
    for table in ["copy_ranges_low", "copy_ranges_high", "copy_ranges_default"] {
        assert_eq!(
            engine
                .sql(&format!("SELECT count(*) AS n FROM {table}"), &[])
                .unwrap()
                .rows[0]["n"],
            Value::Int(1)
        );
    }
}

fn assert_range_copy_output(engine: &Engine) {
    let missing = engine
        .copy_to("COPY copy_ranges(no_such_column) TO STDOUT", Vec::new())
        .unwrap_err();
    assert_eq!(missing.sqlstate(), Some("42703"));
    let generated = engine
        .copy_to("COPY copy_ranges(generated_value) TO STDOUT", Vec::new())
        .unwrap_err();
    assert_eq!(generated.sqlstate(), Some("42P10"));
    let partitioned_to = engine
        .copy_to("COPY copy_ranges TO STDOUT", Vec::new())
        .unwrap_err();
    assert_eq!(partitioned_to.sqlstate(), Some("42809"));
    assert_eq!(
        copy_to_string(engine, "COPY copy_ranges_low TO STDOUT"),
        "1\t1\tone\n"
    );
    assert_eq!(
        copy_to_string(
            engine,
            "COPY (SELECT id, bucket, payload, generated_value FROM copy_ranges ORDER BY id) TO STDOUT",
        ),
        "1\t1\tone\tone:1\n2\t11\ttwo\ttwo:11\n3\t21\tthree\tthree:21\n"
    );
    assert!(copy_to_string(engine, "COPY (SELECT * FROM ONLY copy_ranges) TO STDOUT").is_empty());
}

#[test]
fn range_copy_routes_defaults_generated_identity_and_rolls_back_failures() {
    let engine = Engine::new();
    create_range_copy_fixture(&engine);

    assert_eq!(
        engine
            .copy_from(
                "COPY copy_ranges (bucket, payload) FROM STDIN",
                b"1\tone\n11\ttwo\n21\tthree\n".as_slice(),
            )
            .unwrap(),
        3
    );
    assert_range_copy_rows(&engine);
    assert_range_copy_output(&engine);

    let generated = engine
        .copy_from(
            "COPY copy_ranges (bucket, generated_value) FROM STDIN",
            b"2\tmanual\n".as_slice(),
        )
        .unwrap_err();
    assert_eq!(generated.sqlstate(), Some("42P10"));

    let bound = engine
        .copy_from(
            "COPY copy_ranges_low (bucket, payload) FROM STDIN",
            b"2\twould-rollback\n12\tinvalid\n".as_slice(),
        )
        .unwrap_err();
    assert_eq!(bound.sqlstate(), Some("23514"));
    assert!(engine
        .sql(
            "SELECT * FROM copy_ranges WHERE payload = 'would-rollback'",
            &[],
        )
        .unwrap()
        .rows
        .is_empty());

    let parse = engine
        .copy_from(
            "COPY copy_ranges (bucket, payload) FROM STDIN",
            b"3\twould-rollback\nnot-an-integer\tinvalid\n".as_slice(),
        )
        .unwrap_err();
    assert_eq!(parse.sqlstate(), Some("22P02"));
    assert!(engine
        .sql(
            "SELECT * FROM copy_ranges WHERE payload = 'would-rollback'",
            &[],
        )
        .unwrap()
        .rows
        .is_empty());

    let extra = engine
        .copy_from(
            "COPY copy_ranges (bucket, payload) FROM STDIN",
            b"5\tok\textra\n".as_slice(),
        )
        .unwrap_err();
    assert_eq!(extra.sqlstate(), Some("22P04"));
    let missing = engine
        .copy_from(
            "COPY copy_ranges (bucket, payload) FROM STDIN",
            b"5\n".as_slice(),
        )
        .unwrap_err();
    assert_eq!(missing.sqlstate(), Some("22P04"));
}

#[test]
fn nested_direct_leaf_copy_checks_every_ancestor_and_aborts_transactions_on_format_errors() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE nested_copy_root (id INTEGER, region INTEGER, bucket INTEGER, payload TEXT) PARTITION BY RANGE (region)",
    );
    exec(
        &engine,
        "CREATE TABLE nested_copy_local PARTITION OF nested_copy_root FOR VALUES FROM (0) TO (100) PARTITION BY LIST (bucket)",
    );
    exec(
        &engine,
        "CREATE TABLE nested_copy_local_one PARTITION OF nested_copy_local FOR VALUES IN (1)",
    );
    engine
        .copy_from(
            "COPY nested_copy_root FROM STDIN",
            b"1\t10\t1\trouted\n".as_slice(),
        )
        .unwrap();
    assert_eq!(
        engine
            .sql("SELECT payload FROM nested_copy_local_one", &[])
            .unwrap()
            .rows[0]["payload"],
        Value::Str("routed".into())
    );

    let ancestor_bound = engine
        .copy_from(
            "COPY nested_copy_local_one FROM STDIN",
            b"3\t20\t1\twould-rollback\n2\t150\t1\tinvalid\n".as_slice(),
        )
        .unwrap_err();
    assert_eq!(ancestor_bound.sqlstate(), Some("23514"));
    assert_eq!(
        engine
            .sql("SELECT count(*) AS n FROM nested_copy_root", &[])
            .unwrap()
            .rows[0]["n"],
        Value::Int(1)
    );

    exec(&engine, "BEGIN");
    let format = engine
        .copy_from(
            "COPY nested_copy_root FROM STDIN WITH (FORMAT csv)",
            b"4,30,1,\"unterminated\n".as_slice(),
        )
        .unwrap_err();
    assert_eq!(format.sqlstate(), Some("22P04"));
    let aborted = engine.sql("SELECT 1", &[]).unwrap_err();
    assert_eq!(aborted.sqlstate(), Some("25P02"));
    exec(&engine, "ROLLBACK");

    let header = engine
        .copy_from(
            "COPY nested_copy_root (id, region, bucket, payload) FROM STDIN WITH (FORMAT csv, HEADER MATCH)",
            b"wrong,region,bucket,payload\n5,40,1,nope\n".as_slice(),
        )
        .unwrap_err();
    assert_eq!(header.sqlstate(), Some("22P04"));
    let encoding = engine
        .copy_from("COPY nested_copy_root FROM STDIN", [0xff_u8].as_slice())
        .unwrap_err();
    assert_eq!(encoding.sqlstate(), Some("22021"));
}

#[test]
fn list_hash_default_and_csv_copy_keep_every_physical_row() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE copy_lists (kind TEXT, payload TEXT DEFAULT 'list-default') PARTITION BY LIST (kind)",
    );
    exec(
        &engine,
        "CREATE TABLE copy_lists_known PARTITION OF copy_lists FOR VALUES IN ('a', 'b')",
    );
    exec(
        &engine,
        "CREATE TABLE copy_lists_default PARTITION OF copy_lists DEFAULT",
    );
    assert_eq!(
        engine
            .copy_from(
                "COPY copy_lists (kind, payload) FROM STDIN WITH (FORMAT csv, HEADER MATCH)",
                b"kind,payload\na,plain\nother,\"line\nvalue\"\n,\"\"\n".as_slice(),
            )
            .unwrap(),
        3
    );
    assert_eq!(
        engine
            .sql("SELECT count(*) AS n FROM copy_lists_known", &[])
            .unwrap()
            .rows[0]["n"],
        Value::Int(1)
    );
    assert_eq!(
        engine
            .sql("SELECT count(*) AS n FROM copy_lists_default", &[])
            .unwrap()
            .rows[0]["n"],
        Value::Int(2)
    );
    assert_eq!(
        copy_to_string(
            &engine,
            "COPY (SELECT kind, payload FROM copy_lists ORDER BY kind NULLS LAST) TO STDOUT WITH (FORMAT csv, HEADER)",
        ),
        "kind,payload\na,plain\nother,\"line\nvalue\"\n,\"\"\n"
    );

    exec(
        &engine,
        "CREATE TABLE copy_hashes (key INTEGER, payload TEXT DEFAULT 'hash-default') PARTITION BY HASH (key)",
    );
    exec(
        &engine,
        "CREATE TABLE copy_hashes_0 PARTITION OF copy_hashes FOR VALUES WITH (MODULUS 2, REMAINDER 0)",
    );
    exec(
        &engine,
        "CREATE TABLE copy_hashes_1 PARTITION OF copy_hashes FOR VALUES WITH (MODULUS 2, REMAINDER 1)",
    );
    assert_eq!(
        engine
            .copy_from(
                "COPY copy_hashes (key) FROM STDIN",
                b"1\n2\n3\n4\n\\N\n".as_slice(),
            )
            .unwrap(),
        5
    );
    let physical = engine
        .sql(
            "SELECT _doc_id, key FROM copy_hashes ORDER BY key NULLS LAST",
            &[],
        )
        .unwrap();
    assert_eq!(physical.rows.len(), 5);
    assert!(physical.rows.iter().enumerate().any(|(index, row)| {
        physical.rows[index + 1..]
            .iter()
            .any(|other| row["_doc_id"] == other["_doc_id"])
    }));
    assert_eq!(
        copy_to_string(
            &engine,
            "COPY (SELECT key, payload FROM copy_hashes ORDER BY key NULLS LAST) TO STDOUT",
        )
        .lines()
        .count(),
        5
    );
}

#[test]
fn partition_copy_routing_and_identity_survive_reopen() {
    let directory = tempfile::tempdir().unwrap();
    let database = directory.path().join("copy-hierarchy.db");
    {
        let engine = Engine::open(&database).unwrap();
        exec(
            &engine,
            "CREATE TABLE persistent_copy (id SERIAL, bucket INTEGER, payload TEXT) PARTITION BY RANGE (bucket)",
        );
        exec(
            &engine,
            "CREATE TABLE persistent_copy_low PARTITION OF persistent_copy FOR VALUES FROM (0) TO (10)",
        );
        exec(
            &engine,
            "CREATE TABLE persistent_copy_high PARTITION OF persistent_copy FOR VALUES FROM (10) TO (20)",
        );
        assert_eq!(
            engine
                .copy_from(
                    "COPY persistent_copy (bucket, payload) FROM STDIN",
                    b"1\tone\n11\ttwo\n".as_slice(),
                )
                .unwrap(),
            2
        );
    }

    let reopened = Engine::open(&database).unwrap();
    assert_eq!(
        copy_to_string(
            &reopened,
            "COPY (SELECT id, bucket, payload FROM persistent_copy ORDER BY id) TO STDOUT",
        ),
        "1\t1\tone\n2\t11\ttwo\n"
    );
    reopened
        .copy_from(
            "COPY persistent_copy_high (bucket, payload) FROM STDIN",
            b"12\tthree\n".as_slice(),
        )
        .unwrap();
    let row = reopened
        .sql(
            "SELECT id, payload FROM persistent_copy_high WHERE payload = 'three'",
            &[],
        )
        .unwrap();
    assert_eq!(row.rows[0]["id"], Value::Int(3));
}
