//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! SERIAL default inheritance and identity provenance across relation trees.

use super::exec;
use uqa_core::Value;
use uqa_engine::Engine;
use uqa_sql::ast::{AutoIncrement, AutoIncrementKind, AutoIncrementOwner, ColumnDef, ColumnType};

fn returned_pair(engine: &Engine, sql: &str) -> (i64, i64) {
    let result = engine.sql(sql, &[]).unwrap();
    let Value::Int(serial) = result.rows[0]["serial_id"] else {
        panic!("SERIAL value is not an integer");
    };
    let Value::Int(identity) = result.rows[0]["identity_id"] else {
        panic!("identity value is not an integer");
    };
    (serial, identity)
}

#[test]
fn ordinary_inheritance_shares_serial_but_does_not_inherit_identity() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE generation_parent (serial_id SERIAL, identity_id INTEGER GENERATED BY DEFAULT AS IDENTITY, note TEXT)",
    );
    exec(
        &engine,
        "CREATE TABLE generation_child (extra TEXT) INHERITS (generation_parent)",
    );

    assert_eq!(
        returned_pair(
            &engine,
            "INSERT INTO generation_parent (note) VALUES ('parent') RETURNING serial_id, identity_id",
        ),
        (1, 1)
    );
    assert_eq!(
        returned_pair(
            &engine,
            "INSERT INTO generation_child (identity_id, note, extra) VALUES (100, 'child', 'x') RETURNING serial_id, identity_id",
        ),
        (2, 100)
    );
    assert_eq!(
        returned_pair(
            &engine,
            "INSERT INTO generation_parent (serial_id, identity_id, note) VALUES (DEFAULT, DEFAULT, 'parent-default') RETURNING serial_id, identity_id",
        ),
        (3, 2)
    );
    let missing_identity = engine
        .sql(
            "INSERT INTO generation_child (note, extra) VALUES ('missing', 'x')",
            &[],
        )
        .unwrap_err();
    assert_eq!(missing_identity.sqlstate(), Some("23502"));
    let default_identity = engine
        .sql(
            "INSERT INTO generation_child (serial_id, identity_id, note, extra) VALUES (DEFAULT, DEFAULT, 'default', 'x')",
            &[],
        )
        .unwrap_err();
    assert_eq!(default_identity.sqlstate(), Some("23502"));

    let columns = engine
        .sql(
            "SELECT table_name, column_name, column_default, is_identity, identity_generation FROM information_schema.columns WHERE table_name IN ('generation_parent', 'generation_child') AND column_name IN ('serial_id', 'identity_id') ORDER BY table_name, ordinal_position",
            &[],
        )
        .unwrap();
    assert_eq!(columns.rows.len(), 4);
    assert_eq!(
        columns.rows[0]["table_name"],
        Value::Str("generation_child".into())
    );
    assert_eq!(columns.rows[0]["is_identity"], Value::Str("NO".into()));
    assert!(
        matches!(&columns.rows[0]["column_default"], Value::Str(value) if value.contains("generation_parent_serial_id_seq"))
    );
    assert_eq!(columns.rows[1]["is_identity"], Value::Str("NO".into()));
    assert_eq!(columns.rows[1]["column_default"], Value::Null);
    assert_eq!(columns.rows[2]["is_identity"], Value::Str("NO".into()));
    assert_eq!(columns.rows[3]["is_identity"], Value::Str("YES".into()));
    assert_eq!(
        columns.rows[3]["identity_generation"],
        Value::Str("BY DEFAULT".into())
    );
    let sequences = engine
        .sql(
            "SELECT sequencename FROM pg_catalog.pg_sequences WHERE sequencename IN ('generation_parent_serial_id_seq', 'generation_parent_identity_id_seq') ORDER BY sequencename",
            &[],
        )
        .unwrap();
    assert_eq!(sequences.rows.len(), 2);
    assert_eq!(
        sequences.rows[0]["sequencename"],
        Value::Str("generation_parent_identity_id_seq".into())
    );
    assert_eq!(
        sequences.rows[1]["sequencename"],
        Value::Str("generation_parent_serial_id_seq".into())
    );
}

fn seed_persistent_generation_hierarchy(database: &std::path::Path) {
    let engine = Engine::open(database).unwrap();
    exec(
        &engine,
        "CREATE TABLE durable_generation_parent (serial_id SERIAL, identity_id INTEGER GENERATED BY DEFAULT AS IDENTITY, note TEXT)",
    );
    exec(
        &engine,
        "CREATE TABLE durable_generation_child (extra TEXT) INHERITS (durable_generation_parent)",
    );
    assert_eq!(
        returned_pair(
            &engine,
            "INSERT INTO durable_generation_parent (note) VALUES ('parent') RETURNING serial_id, identity_id",
        ),
        (1, 1)
    );
    assert_eq!(
        returned_pair(
            &engine,
            "INSERT INTO durable_generation_child (identity_id, note, extra) VALUES (100, 'child', 'x') RETURNING serial_id, identity_id",
        ),
        (2, 100)
    );
}

#[test]
fn inherited_sequence_ownership_survives_reopen_and_drives_truncate_restart() {
    let directory = tempfile::tempdir().unwrap();
    let database = directory.path().join("identity-provenance.db");
    seed_persistent_generation_hierarchy(&database);

    let engine = Engine::open(&database).unwrap();
    assert_eq!(
        returned_pair(
            &engine,
            "INSERT INTO durable_generation_child (identity_id, note, extra) VALUES (101, 'reopened-child', 'x') RETURNING serial_id, identity_id",
        ),
        (3, 101)
    );
    exec(
        &engine,
        "TRUNCATE durable_generation_child RESTART IDENTITY",
    );
    assert_eq!(
        returned_pair(
            &engine,
            "INSERT INTO durable_generation_child (identity_id, note, extra) VALUES (102, 'child-restart', 'x') RETURNING serial_id, identity_id",
        ),
        (4, 102)
    );
    exec(
        &engine,
        "TRUNCATE durable_generation_parent CONTINUE IDENTITY",
    );
    assert_eq!(
        returned_pair(
            &engine,
            "INSERT INTO durable_generation_parent (note) VALUES ('continued') RETURNING serial_id, identity_id",
        ),
        (5, 2)
    );
    exec(
        &engine,
        "TRUNCATE durable_generation_parent RESTART IDENTITY",
    );
    assert_eq!(
        returned_pair(
            &engine,
            "INSERT INTO durable_generation_parent (note) VALUES ('restarted') RETURNING serial_id, identity_id",
        ),
        (1, 1)
    );
    drop(engine);

    let reopened = Engine::open(&database).unwrap();
    assert_eq!(
        returned_pair(
            &reopened,
            "INSERT INTO durable_generation_parent (note) VALUES ('reopened-again') RETURNING serial_id, identity_id",
        ),
        (2, 2)
    );
}

#[test]
fn legacy_boolean_auto_increment_metadata_remains_readable() {
    let legacy_true =
        r#"{"name":"id","ty":"Integer","primary_key":false,"not_null":true,"auto_increment":true}"#;
    let legacy: ColumnDef = serde_json::from_str(legacy_true).unwrap();
    assert_eq!(
        legacy.auto_increment.as_ref().map(|value| value.kind),
        Some(AutoIncrementKind::Legacy)
    );

    let current = ColumnDef {
        name: "id".into(),
        ty: ColumnType::Integer,
        object_id: None,
        missing_value: None,
        primary_key: false,
        not_null: true,
        not_null_explicit: false,
        not_null_name: None,
        not_null_validated: true,
        not_null_no_inherit: false,
        auto_increment: Some(AutoIncrement {
            kind: AutoIncrementKind::Serial,
            sequence: Some("public.parent_id_seq".into()),
            owner: Some(AutoIncrementOwner {
                table: "public.parent".into(),
                column: "id".into(),
            }),
        }),
        unique: false,
        default: None,
        generated: None,
        check: None,
        check_name: None,
        check_enforced: true,
        check_validated: true,
        check_no_inherit: false,
        references: None,
    };
    let round_trip: ColumnDef =
        serde_json::from_str(&serde_json::to_string(&current).unwrap()).unwrap();
    assert_eq!(round_trip.auto_increment, current.auto_increment);
}

#[test]
fn legacy_boolean_auto_increment_catalog_fields_are_internally_consistent() {
    let directory = tempfile::tempdir().unwrap();
    let database = directory.path().join("legacy-auto-increment-catalog.db");
    {
        let engine = Engine::open(&database).unwrap();
        exec(&engine, "CREATE TABLE legacy_catalog (id SERIAL)");
    }
    {
        let connection = rusqlite::Connection::open(&database).unwrap();
        let columns: String = connection
            .query_row(
                "SELECT columns FROM _tables WHERE schema_name = 'public' AND relation_name = 'legacy_catalog'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        let mut columns: serde_json::Value = serde_json::from_str(&columns).unwrap();
        columns[0]["auto_increment"] = serde_json::Value::Bool(true);
        connection
            .execute(
                "UPDATE _tables SET columns = ?1 WHERE schema_name = 'public' AND relation_name = 'legacy_catalog'",
                [serde_json::to_string(&columns).unwrap()],
            )
            .unwrap();
    }
    let reopened = Engine::open(&database).unwrap();
    let column = reopened
        .sql(
            "SELECT is_identity, identity_generation, identity_start, identity_increment FROM information_schema.columns WHERE table_name = 'legacy_catalog' AND column_name = 'id'",
            &[],
        )
        .unwrap();
    assert_eq!(column.rows[0]["is_identity"], Value::Str("YES".into()));
    assert_eq!(
        column.rows[0]["identity_generation"],
        Value::Str("BY DEFAULT".into())
    );
    assert_eq!(column.rows[0]["identity_start"], Value::Str("1".into()));
    assert_eq!(column.rows[0]["identity_increment"], Value::Str("1".into()));
}
