//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! Fixed record, unknown and catalog-row type metadata.

use super::{schema_oid, PgTypeCatalogMetadata, PgTypeRoutineOids};

#[expect(
    clippy::too_many_lines,
    reason = "preserves fixed catalog metadata order"
)]
pub(super) fn metadata() -> impl Iterator<Item = PgTypeCatalogMetadata<'static>> {
    [
        PgTypeCatalogMetadata {
            oid: 2249,
            name: "record".into(),
            namespace_oid: schema_oid("pg_catalog"),
            len: -1,
            by_value: false,
            kind: "p",
            category: "P",
            preferred: false,
            relation_oid: 0,
            subscript: 0,
            element_oid: 0,
            array_oid: 2287,
            routines: PgTypeRoutineOids {
                input: 2290,
                output: 2291,
                receive: 2402,
                send: 2403,
                modifier_input: 0,
                modifier_output: 0,
                analyze: 0,
            },
            align: "d",
            storage: "x",
            base_oid: 0,
            type_modifier: -1,
            collation_oid: 0,
        },
        PgTypeCatalogMetadata {
            oid: 705,
            name: "unknown".into(),
            namespace_oid: schema_oid("pg_catalog"),
            len: -2,
            by_value: false,
            kind: "p",
            category: "X",
            preferred: false,
            relation_oid: 0,
            subscript: 0,
            element_oid: 0,
            array_oid: 0,
            routines: PgTypeRoutineOids {
                input: 109,
                output: 110,
                receive: 2416,
                send: 2417,
                modifier_input: 0,
                modifier_output: 0,
                analyze: 0,
            },
            align: "c",
            storage: "p",
            base_oid: 0,
            type_modifier: -1,
            collation_oid: 0,
        },
        PgTypeCatalogMetadata {
            oid: 2278,
            name: "void".into(),
            namespace_oid: schema_oid("pg_catalog"),
            len: 4,
            by_value: true,
            kind: "p",
            category: "P",
            preferred: false,
            relation_oid: 0,
            subscript: 0,
            element_oid: 0,
            array_oid: 0,
            routines: PgTypeRoutineOids {
                input: 2298,
                output: 2299,
                receive: 3120,
                send: 3121,
                modifier_input: 0,
                modifier_output: 0,
                analyze: 0,
            },
            align: "i",
            storage: "p",
            base_oid: 0,
            type_modifier: -1,
            collation_oid: 0,
        },
        PgTypeCatalogMetadata {
            oid: 2287,
            name: "_record".into(),
            namespace_oid: schema_oid("pg_catalog"),
            len: -1,
            by_value: false,
            kind: "p",
            category: "P",
            preferred: false,
            relation_oid: 0,
            subscript: 6179,
            element_oid: 2249,
            array_oid: 0,
            routines: PgTypeRoutineOids {
                input: 750,
                output: 751,
                receive: 2400,
                send: 2401,
                modifier_input: 0,
                modifier_output: 0,
                analyze: 3816,
            },
            align: "d",
            storage: "x",
            base_oid: 0,
            type_modifier: -1,
            collation_oid: 0,
        },
        PgTypeCatalogMetadata {
            oid: 13_314,
            name: "_information_schema_catalog_name".into(),
            namespace_oid: schema_oid("information_schema"),
            len: -1,
            by_value: false,
            kind: "b",
            category: "A",
            preferred: false,
            relation_oid: 0,
            subscript: 6179,
            element_oid: 13_315,
            array_oid: 0,
            routines: PgTypeRoutineOids {
                input: 750,
                output: 751,
                receive: 2400,
                send: 2401,
                modifier_input: 0,
                modifier_output: 0,
                analyze: 3816,
            },
            align: "d",
            storage: "x",
            base_oid: 0,
            type_modifier: -1,
            collation_oid: 0,
        },
        PgTypeCatalogMetadata {
            oid: 13_315,
            name: "information_schema_catalog_name".into(),
            namespace_oid: schema_oid("information_schema"),
            len: -1,
            by_value: false,
            kind: "c",
            category: "C",
            preferred: false,
            relation_oid: 13_313,
            subscript: 0,
            element_oid: 0,
            array_oid: 13_314,
            routines: PgTypeRoutineOids {
                input: 2290,
                output: 2291,
                receive: 2402,
                send: 2403,
                modifier_input: 0,
                modifier_output: 0,
                analyze: 0,
            },
            align: "d",
            storage: "x",
            base_oid: 0,
            type_modifier: -1,
            collation_oid: 0,
        },
    ]
    .into_iter()
}
