//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! `PostgreSQL` role and object privilege inquiry routine identities.

use super::BuiltinRoutineCatalogEntry;

pub(super) const ROUTINES: &[BuiltinRoutineCatalogEntry] = &[
    BuiltinRoutineCatalogEntry {
        oid: 1922,
        name: "has_table_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_table_privilege_name_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1923,
        name: "has_table_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_table_privilege_name_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1924,
        name: "has_table_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_table_privilege_id_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1925,
        name: "has_table_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_table_privilege_id_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1926,
        name: "has_table_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_table_privilege_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1927,
        name: "has_table_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_table_privilege_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2181,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_name_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2182,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_name_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2183,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_id_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2184,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_id_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2185,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2186,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2250,
        name: "has_database_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_database_privilege_name_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2251,
        name: "has_database_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_database_privilege_name_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2252,
        name: "has_database_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_database_privilege_id_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2253,
        name: "has_database_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_database_privilege_id_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2254,
        name: "has_database_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_database_privilege_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2255,
        name: "has_database_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_database_privilege_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2268,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_name_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2269,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_name_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2270,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_id_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2271,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_id_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2272,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2273,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2705,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 19, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_name_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2706,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_name_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2707,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 19, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_id_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2708,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_id_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2709,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2710,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_id",
    },
];
