//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

use super::{BuiltinRoutineCatalogEntry, FALSE_NODE};

pub(super) const ROUTINES: &[BuiltinRoutineCatalogEntry] = &[
    BuiltinRoutineCatalogEntry {
        oid: 2212,
        name: "regprocedurein",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 2202,
        argument_types: &[2275],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "regprocedurein",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2213,
        name: "regprocedureout",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 2275,
        argument_types: &[2202],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "regprocedureout",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2446,
        name: "regprocedurerecv",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2202,
        argument_types: &[2281],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "regprocedurerecv",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2447,
        name: "regproceduresend",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 17,
        argument_types: &[2202],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "regproceduresend",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3479,
        name: "to_regprocedure",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 2202,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_regprocedure",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3493,
        name: "to_regtype",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 2206,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_regtype",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3494,
        name: "to_regproc",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 24,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_regproc",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3495,
        name: "to_regclass",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 2205,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_regclass",
    },
    BuiltinRoutineCatalogEntry {
        oid: 4086,
        name: "to_regnamespace",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 4089,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_regnamespace",
    },
    BuiltinRoutineCatalogEntry {
        oid: 4092,
        name: "regroleout",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 2275,
        argument_types: &[4096],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "regroleout",
    },
    BuiltinRoutineCatalogEntry {
        oid: 4093,
        name: "to_regrole",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 4096,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_regrole",
    },
    BuiltinRoutineCatalogEntry {
        oid: 4094,
        name: "regrolerecv",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 4096,
        argument_types: &[2281],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "regrolerecv",
    },
    BuiltinRoutineCatalogEntry {
        oid: 4095,
        name: "regrolesend",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 17,
        argument_types: &[4096],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "regrolesend",
    },
    BuiltinRoutineCatalogEntry {
        oid: 4098,
        name: "regrolein",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 4096,
        argument_types: &[2275],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "regrolein",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1574,
        name: "nextval",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "u",
        leakproof: false,
        return_type: 20,
        argument_types: &[2205],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "nextval_oid",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1575,
        name: "currval",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "u",
        leakproof: false,
        return_type: 20,
        argument_types: &[2205],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "currval_oid",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2559,
        name: "lastval",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "u",
        leakproof: false,
        return_type: 20,
        argument_types: &[],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "lastval",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1576,
        name: "setval",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "u",
        leakproof: false,
        return_type: 20,
        argument_types: &[2205, 20],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "setval_oid",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1765,
        name: "setval",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "u",
        leakproof: false,
        return_type: 20,
        argument_types: &[2205, 20, 16],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "setval3_oid",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1665,
        name: "pg_get_serial_sequence",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_serial_sequence",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1716,
        name: "pg_get_expr",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[194, 26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_expr",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2509,
        name: "pg_get_expr",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[194, 26, 16],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_expr_ext",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3352,
        name: "pg_get_partkeydef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_partkeydef",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1662,
        name: "pg_get_triggerdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_triggerdef",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2730,
        name: "pg_get_triggerdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26, 16],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_triggerdef_ext",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1573,
        name: "pg_get_ruledef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_ruledef",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2504,
        name: "pg_get_ruledef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26, 16],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_ruledef_ext",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2181,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_name_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2182,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_name_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2183,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_id_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2184,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_id_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2185,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2186,
        name: "has_sequence_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_sequence_privilege_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2268,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_name_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2269,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_name_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2270,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_id_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2271,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_id_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2272,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[25, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2273,
        name: "has_schema_privilege",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "has_schema_privilege_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2705,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 19, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_name_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2706,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_name_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2707,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 19, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_id_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2708,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_id_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2709,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[19, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2710,
        name: "pg_has_role",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 16,
        argument_types: &[26, 25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_has_role_id",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6381,
        name: "array_reverse",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_reverse",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6388,
        name: "array_sort",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_sort",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6389,
        name: "array_sort",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277, 16],
        argument_names: &["array", "descending"],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_sort_order",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6390,
        name: "array_sort",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277, 16, 16],
        argument_names: &["array", "descending", "nulls_first"],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_sort_order_nulls_first",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1810,
        name: "bit_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1811,
        name: "bit_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6412,
        name: "casefold",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "casefold",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1372,
        name: "char_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[1042],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "bpcharlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1381,
        name: "char_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "textlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1367,
        name: "character_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[1042],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "bpcharlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1369,
        name: "character_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "textlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6364,
        name: "crc32",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: true,
        return_type: 20,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "crc32_bytea",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6365,
        name: "crc32c",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: true,
        return_type: 20,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "crc32c_bytea",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6383,
        name: "gamma",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 701,
        argument_types: &[701],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "dgamma",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6384,
        name: "lgamma",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 701,
        argument_types: &[701],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "dlgamma",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1317,
        name: "length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "textlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1318,
        name: "length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[1042],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "bpcharlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2010,
        name: "length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "byteaoctetlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3261,
        name: "json_strip_nulls",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 114,
        argument_types: &[114, 16],
        argument_names: &["target", "strip_in_arrays"],
        default_arguments: 1,
        argument_defaults: Some(FALSE_NODE),
        source: "json_strip_nulls",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3262,
        name: "jsonb_strip_nulls",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 3802,
        argument_types: &[3802, 16],
        argument_names: &["target", "strip_in_arrays"],
        default_arguments: 1,
        argument_defaults: Some(FALSE_NODE),
        source: "jsonb_strip_nulls",
    },
];
