//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

use super::*;

pub(super) fn assert_rule_projection_defaults_returning_and_command_tags() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE default_rule_base (id INTEGER DEFAULT 5, value INTEGER);
         CREATE TABLE default_rule_log (id INTEGER);
         CREATE RULE default_rule AS ON INSERT TO default_rule_base
           DO ALSO INSERT INTO default_rule_log VALUES (NEW.id)",
    );
    exec(&engine, "INSERT INTO default_rule_base (value) VALUES (10)");
    assert_eq!(
        exec(&engine, "SELECT id FROM default_rule_log").rows[0]["id"],
        Value::Int(5)
    );
    exec(
        &engine,
        "CREATE TABLE identity_rule_base (
           id BIGINT GENERATED BY DEFAULT AS IDENTITY,
           value INTEGER
         );
         CREATE TABLE identity_rule_log (id BIGINT);
         CREATE RULE identity_rule AS ON INSERT TO identity_rule_base
           DO INSTEAD INSERT INTO identity_rule_log VALUES (NEW.id)",
    );
    let identity = exec(
        &engine,
        "INSERT INTO identity_rule_base (value) VALUES (10)",
    );
    assert_eq!(identity.affected_rows, 1);
    assert_eq!(
        exec(&engine, "SELECT id FROM identity_rule_log").rows[0]["id"],
        Value::Int(1)
    );

    exec(
        &engine,
        "CREATE TABLE conditional_projection_base (id INTEGER PRIMARY KEY);
         CREATE TABLE conditional_projection_log (value INTEGER);
         CREATE VIEW conditional_projection_view AS
           SELECT id, 1 / id AS danger FROM conditional_projection_base;
         CREATE RULE conditional_projection_rule AS ON INSERT TO conditional_projection_view
           WHERE NEW.id < 0
           DO ALSO INSERT INTO conditional_projection_log VALUES (NEW.danger)",
    );
    exec(
        &engine,
        "INSERT INTO conditional_projection_view (id) VALUES (0)",
    );
    assert_eq!(
        exec(
            &engine,
            "SELECT count(*) AS total FROM conditional_projection_log"
        )
        .rows[0]["total"],
        Value::Int(0)
    );

    exec(
        &engine,
        "CREATE TABLE provider_base (id INTEGER, value TEXT);
         CREATE TABLE provider_action (id INTEGER, value TEXT);
         CREATE VIEW provider_view (item_id, label) AS SELECT id, value FROM provider_base;
         CREATE RULE provider_rule AS ON INSERT TO provider_view
           DO INSTEAD INSERT INTO provider_action VALUES (NEW.item_id, NEW.label)
           RETURNING id, value",
    );
    let provider = exec(
        &engine,
        "INSERT INTO provider_view VALUES (1, 'one') RETURNING (SELECT label) AS got",
    );
    assert_eq!(provider.rows[0]["got"], Value::Str("one".into()));

    exec(
        &engine,
        "CREATE TABLE unrouted_tableoid_base (id INTEGER);
         CREATE TABLE unrouted_tableoid_log (was_null BOOLEAN);
         CREATE VIEW unrouted_tableoid_view AS
           SELECT id, tableoid AS physical_oid FROM unrouted_tableoid_base;
         CREATE RULE unrouted_tableoid_rule AS ON INSERT TO unrouted_tableoid_view
           DO INSTEAD INSERT INTO unrouted_tableoid_log VALUES (NEW.physical_oid IS NULL)",
    );
    let suppressed = exec(
        &engine,
        "INSERT INTO unrouted_tableoid_view (id) VALUES (1)",
    );
    assert_eq!(suppressed.affected_rows, 1);
    assert_eq!(
        exec(&engine, "SELECT was_null FROM unrouted_tableoid_log").rows[0]["was_null"],
        Value::Bool(true)
    );
}

pub(super) fn assert_nested_rule_returning_provider_and_lazy_projection() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE nested_returning_base (id INTEGER PRIMARY KEY, value INTEGER NOT NULL);
         CREATE TABLE nested_returning_action (id INTEGER, value INTEGER);
         CREATE TABLE nested_returning_log (id INTEGER);
         CREATE VIEW nested_returning_inner AS SELECT id, value FROM nested_returning_base;
         CREATE VIEW nested_returning_outer AS SELECT id, value FROM nested_returning_inner;
         CREATE RULE nested_returning_inner_rule AS ON INSERT TO nested_returning_inner
           DO INSTEAD INSERT INTO nested_returning_action VALUES (NEW.id, NEW.value)
           RETURNING id, value;
         CREATE RULE nested_returning_outer_rule AS ON INSERT TO nested_returning_outer
           DO ALSO INSERT INTO nested_returning_log VALUES (NEW.id)",
    );
    let returned = exec(
        &engine,
        "INSERT INTO nested_returning_outer VALUES (1, 10) RETURNING id, value",
    );
    assert_eq!(returned.rows.len(), 1);
    assert_eq!(returned.rows[0]["id"], Value::Int(1));
    assert_eq!(returned.rows[0]["value"], Value::Int(10));

    exec(
        &engine,
        "CREATE TABLE lazy_projection_base (id INTEGER PRIMARY KEY);
         CREATE TABLE lazy_projection_log (id INTEGER);
         CREATE VIEW lazy_projection_view AS
           SELECT id, 1 / (id - id) AS boom FROM lazy_projection_base;
         CREATE RULE lazy_projection_rule AS ON INSERT TO lazy_projection_view
           DO INSTEAD INSERT INTO lazy_projection_log VALUES (NEW.id)",
    );
    exec(&engine, "INSERT INTO lazy_projection_view (id) VALUES (1)");
    let logged = exec(&engine, "SELECT id FROM lazy_projection_log");
    assert_eq!(logged.rows[0]["id"], Value::Int(1));
}

pub(super) fn assert_update_from_delete_using_returning_and_visibility() {
    let engine = automatic_view_engine();
    exec(
        &engine,
        "INSERT INTO automatic_items (item_id, label) VALUES (1, 'one'), (2, 'two'), (3, 'three')",
    );
    exec(
        &engine,
        "CREATE TABLE automatic_source (id INTEGER PRIMARY KEY, next_value TEXT NOT NULL)",
    );
    exec(
        &engine,
        "INSERT INTO automatic_source VALUES (1, 'updated'), (3, 'removed')",
    );
    exec(
        &engine,
        "CREATE TABLE automatic_ambiguous_source (item_id INTEGER PRIMARY KEY, label TEXT NOT NULL)",
    );
    exec(
        &engine,
        "INSERT INTO automatic_ambiguous_source VALUES (2, 'ambiguous')",
    );

    for sql in [
        "UPDATE automatic_items SET label = 'wrong'
         FROM automatic_ambiguous_source AS source
         WHERE item_id = source.item_id",
        "DELETE FROM automatic_items USING automatic_ambiguous_source AS source
         WHERE item_id = source.item_id",
    ] {
        let error = engine.sql(sql, &[]).unwrap_err();
        assert_eq!(error.sqlstate(), Some("42702"), "{sql}: {error}");
    }
    assert_eq!(
        exec(
            &engine,
            "SELECT label FROM automatic_items WHERE item_id = 2"
        )
        .rows[0]["label"],
        Value::Str("two".into())
    );

    let updated = exec(
        &engine,
        "UPDATE automatic_items AS target SET label = source.next_value || ':from'
         FROM automatic_source AS source
         WHERE target.item_id = source.id AND source.id = 1
         RETURNING target.item_id, source.next_value, label, doubled",
    );
    assert_eq!(updated.rows[0]["item_id"], Value::Int(1));
    assert_eq!(updated.rows[0]["next_value"], Value::Str("updated".into()));
    assert_eq!(updated.rows[0]["label"], Value::Str("updated:from".into()));
    assert_eq!(updated.rows[0]["doubled"], Value::Int(14));

    let hidden = exec(
        &engine,
        "UPDATE automatic_items SET visible = false WHERE item_id = 2
         RETURNING item_id, visible, doubled",
    );
    assert_eq!(hidden.rows[0]["visible"], Value::Bool(false));
    assert!(
        exec(&engine, "SELECT * FROM automatic_items WHERE item_id = 2")
            .rows
            .is_empty()
    );

    let deleted = exec(
        &engine,
        "DELETE FROM automatic_items AS target USING automatic_source AS source
         WHERE target.item_id = source.id AND source.id = 3
         RETURNING target.item_id, source.next_value, label, doubled",
    );
    assert_eq!(deleted.rows[0]["item_id"], Value::Int(3));
    assert_eq!(deleted.rows[0]["next_value"], Value::Str("removed".into()));
    assert_eq!(deleted.rows[0]["label"], Value::Str("three".into()));
    assert_eq!(deleted.rows[0]["doubled"], Value::Int(14));

    assert_update_from_delete_using_returning_stars(&engine);
}

fn assert_update_from_delete_using_returning_stars(engine: &Engine) {
    exec(
        engine,
        "INSERT INTO automatic_items (item_id, label) VALUES (5, 'five'), (6, 'six')",
    );
    exec(
        engine,
        "INSERT INTO automatic_source VALUES (5, 'star-update'), (6, 'star-delete')",
    );
    let update_star = exec(
        engine,
        "UPDATE automatic_items AS target SET label = source.next_value
         FROM automatic_source AS source
         WHERE target.item_id = source.id AND source.id = 5
         RETURNING *",
    );
    assert_eq!(
        update_star.columns,
        ["item_id", "label", "visible", "doubled", "id", "next_value"]
    );
    assert_eq!(update_star.value_at(0, 0), Some(&Value::Int(5)));
    assert_eq!(
        update_star.value_at(0, 4),
        Some(&Value::Int(5)),
        "RETURNING * must append the FROM row after the target view row"
    );
    assert_eq!(
        update_star.value_at(0, 5),
        Some(&Value::Str("star-update".into()))
    );
    let delete_star = exec(
        engine,
        "DELETE FROM automatic_items AS target USING automatic_source AS source
         WHERE target.item_id = source.id AND source.id = 6
         RETURNING *",
    );
    assert_eq!(
        delete_star.columns,
        ["item_id", "label", "visible", "doubled", "id", "next_value"]
    );
    assert_eq!(delete_star.value_at(0, 0), Some(&Value::Int(6)));
    assert_eq!(delete_star.value_at(0, 4), Some(&Value::Int(6)));
    assert_eq!(
        delete_star.value_at(0, 5),
        Some(&Value::Str("star-delete".into()))
    );
}

pub(super) fn assert_view_row_type_is_the_dml_name_boundary() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE row_type_base (
            id INTEGER PRIMARY KEY,
            shown TEXT NOT NULL,
            secret TEXT NOT NULL
        );
         INSERT INTO row_type_base VALUES (1, 'shown', 'secret');
         CREATE VIEW row_type_view AS SELECT id, shown FROM row_type_base",
    );
    for sql in [
        "UPDATE row_type_view SET shown = secret WHERE id = 1",
        "UPDATE row_type_view SET shown = 'leaked' WHERE secret = 'secret'",
        "UPDATE row_type_view SET shown = 'leaked' WHERE id = 1 RETURNING secret",
        "INSERT INTO row_type_view (id, shown) VALUES (2, 'two') RETURNING secret",
    ] {
        let error = engine.sql(sql, &[]).unwrap_err();
        assert_eq!(error.sqlstate(), Some("42703"), "{sql}: {error}");
    }
    let unchanged = exec(&engine, "SELECT shown FROM row_type_base WHERE id = 1");
    assert_eq!(unchanged.rows[0]["shown"], Value::Str("shown".into()));
    assert!(exec(&engine, "SELECT * FROM row_type_base WHERE id = 2")
        .rows
        .is_empty());

    exec(
        &engine,
        "CREATE VIEW duplicate_mapping (first_id, second_id) AS
         SELECT id, id FROM row_type_base",
    );
    let duplicate = engine
        .sql(
            "UPDATE duplicate_mapping SET first_id = 2, second_id = 3",
            &[],
        )
        .unwrap_err();
    assert_eq!(duplicate.sqlstate(), Some("42601"));

    exec(
        &engine,
        "INSERT INTO row_type_base VALUES (2, 'shown-two', 'base-secret-two');
         CREATE TABLE row_type_source (id INTEGER PRIMARY KEY, secret TEXT NOT NULL);
         INSERT INTO row_type_source VALUES (1, 'source-secret'), (2, 'delete-secret')",
    );
    let updated = exec(
        &engine,
        "UPDATE row_type_view SET shown = secret
         FROM row_type_source AS source
         WHERE row_type_view.id = source.id AND source.id = 1
         RETURNING shown, secret AS source_secret",
    );
    assert_eq!(updated.rows[0]["shown"], Value::Str("source-secret".into()));
    assert_eq!(
        updated.rows[0]["source_secret"],
        Value::Str("source-secret".into())
    );
    let deleted = exec(
        &engine,
        "DELETE FROM row_type_view USING row_type_source AS source
         WHERE row_type_view.id = source.id AND secret = 'delete-secret'
         RETURNING row_type_view.id, secret AS source_secret",
    );
    assert_eq!(deleted.rows[0]["id"], Value::Int(2));
    assert_eq!(
        deleted.rows[0]["source_secret"],
        Value::Str("delete-secret".into())
    );
}

pub(super) fn assert_source_old_and_new_aliases_remain_source_relations() {
    let engine = Engine::new();
    exec(
        &engine,
        "CREATE TABLE alias_base (id INTEGER PRIMARY KEY, label TEXT NOT NULL);
         CREATE VIEW alias_view AS SELECT id, label FROM alias_base;
         CREATE TABLE alias_source (id INTEGER PRIMARY KEY, label TEXT NOT NULL);
         INSERT INTO alias_base VALUES (1, 'one'), (2, 'two');
         INSERT INTO alias_source VALUES (1, 'new-source'), (2, 'old-source')",
    );
    let updated = exec(
        &engine,
        "UPDATE alias_view AS target SET label = new.label
         FROM alias_source AS new
         WHERE target.id = new.id AND new.id = 1
         RETURNING target.id, new.label AS source_label, target.label",
    );
    assert_eq!(updated.rows[0]["id"], Value::Int(1));
    assert_eq!(
        updated.rows[0]["source_label"],
        Value::Str("new-source".into())
    );
    assert_eq!(updated.rows[0]["label"], Value::Str("new-source".into()));
    let deleted = exec(
        &engine,
        "DELETE FROM alias_view AS target USING alias_source AS old
         WHERE target.id = old.id AND old.id = 2
         RETURNING target.id, old.label AS source_label",
    );
    assert_eq!(deleted.rows[0]["id"], Value::Int(2));
    assert_eq!(
        deleted.rows[0]["source_label"],
        Value::Str("old-source".into())
    );
}
