//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! An identity column's sequence takes the options its declaration writes, which `PostgreSQL` reads, completes and checks as `CREATE SEQUENCE` does, and `CREATE SEQUENCE` reads `RESTART` as well. A `SERIAL` or identity column added to a table creates its sequence and numbers the rows the table holds. The expected values and errors are those of `PostgreSQL` 18.4.

use super::*;

/// Run `scenario` on a memory engine and on each persistent layout, then `reopened` on each layout after the engine that ran the scenario closed.
fn on_every_engine(scenario: impl Fn(&Engine, &str), reopened: impl Fn(&Engine, &str)) {
    scenario(&Engine::new(), "memory");
    for layout in LAYOUTS {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("identity-sequences.db");
        let label = format!("{layout:?}");
        scenario(&open(layout, &path), &label);
        reopened(&open(layout, &path), &label);
    }
}

/// The SQLSTATE and message of the error `statement` fails with.
fn error(engine: &Engine, statement: &str) -> (String, String) {
    let error = engine
        .sql(statement, &[])
        .expect_err(&format!("{statement} must fail"));
    (
        error.sqlstate().unwrap_or_default().to_owned(),
        error.to_string(),
    )
}

fn declared_rows(engine: &Engine, label: &str) {
    for (query, columns, expected) in [
        ("SELECT id, v FROM stepped ORDER BY v", &["id", "v"][..], vec!["10|1", "15|2"]),
        ("SELECT id, v FROM cycled ORDER BY v", &["id", "v"], vec!["3|1", "4|2", "3|3"]),
        ("SELECT id, v FROM descending ORDER BY v", &["id", "v"], vec!["-1|1", "-2|2"]),
        ("SELECT id FROM restarted", &["id"], vec!["3"]),
        ("SELECT id FROM unlogged_ids", &["id"], vec!["1"]),
        (
            "SELECT pg_get_serial_sequence('cycled', 'id') AS name",
            &["name"],
            vec!["public.cycled_ids"],
        ),
        (
            "SELECT table_name, identity_start, identity_increment, identity_maximum, identity_minimum, identity_cycle FROM information_schema.columns WHERE column_name = 'id' AND table_name IN ('stepped', 'cycled', 'descending') ORDER BY table_name",
            &[
                "table_name",
                "identity_start",
                "identity_increment",
                "identity_maximum",
                "identity_minimum",
                "identity_cycle",
            ],
            vec![
                "cycled|3|1|4|3|YES",
                "descending|-1|-1|-1|-2147483648|NO",
                "stepped|10|5|2147483647|1|NO",
            ],
        ),
    ] {
        assert_eq!(rows(engine, query, columns), expected, "{label}: {query}");
    }
}

#[test]
fn identity_sequences_take_the_options_their_declarations_write() {
    on_every_engine(
        |engine, label| {
            run(
                engine,
                "CREATE TABLE stepped (id int GENERATED ALWAYS AS IDENTITY (START WITH 10 INCREMENT BY 5), v int);
                 INSERT INTO stepped (v) VALUES (1), (2);
                 CREATE TABLE cycled (id smallint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME cycled_ids MINVALUE 3 MAXVALUE 4 CYCLE CACHE 2), v int);
                 INSERT INTO cycled (v) VALUES (1), (2), (3);
                 CREATE TABLE descending (id int GENERATED ALWAYS AS IDENTITY (INCREMENT BY -1), v int);
                 INSERT INTO descending (v) VALUES (1), (2);
                 CREATE TABLE restarted (id int GENERATED ALWAYS AS IDENTITY (START 1 RESTART 3 INCREMENT 2));
                 INSERT INTO restarted DEFAULT VALUES;
                 CREATE TABLE unlogged_ids (id int GENERATED ALWAYS AS IDENTITY (UNLOGGED OWNED BY NONE));
                 INSERT INTO unlogged_ids DEFAULT VALUES;
                 CREATE TABLE capped (id int GENERATED ALWAYS AS IDENTITY (MAXVALUE 2));
                 INSERT INTO capped DEFAULT VALUES;
                 INSERT INTO capped DEFAULT VALUES",
            );
            assert_eq!(
                error(engine, "INSERT INTO capped DEFAULT VALUES"),
                (
                    "2200H".into(),
                    "nextval: reached maximum value of sequence \"capped_id_seq\" (2)".into()
                ),
                "{label}"
            );
            declared_rows(engine, label);
        },
        declared_rows,
    );
}

#[test]
fn identity_declarations_fail_as_postgresql_does() {
    let engine = Engine::new();
    run(&engine, "CREATE SEQUENCE taken");
    let conflicting = || {
        (
            "42601".to_owned(),
            "conflicting or redundant options".to_owned(),
        )
    };
    for (statement, expected) in [
        // The column's type comes first, as an `AS` that a written one repeats.
        (
            "CREATE TABLE failed (id int GENERATED ALWAYS AS IDENTITY (AS bigint))",
            conflicting(),
        ),
        (
            "CREATE TABLE failed (id int GENERATED ALWAYS AS IDENTITY (START 1 START 2))",
            conflicting(),
        ),
        (
            "CREATE TABLE failed (id int GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME a SEQUENCE NAME b))",
            conflicting(),
        ),
        (
            "CREATE TABLE failed (id int GENERATED ALWAYS AS IDENTITY (LOGGED UNLOGGED))",
            conflicting(),
        ),
        (
            "CREATE TABLE failed (id text GENERATED ALWAYS AS IDENTITY)",
            (
                "22023".into(),
                "identity column type must be smallint, integer, or bigint".into(),
            ),
        ),
        (
            "CREATE TABLE failed (id numeric GENERATED ALWAYS AS IDENTITY)",
            (
                "22023".into(),
                "identity column type must be smallint, integer, or bigint".into(),
            ),
        ),
        (
            "CREATE TABLE failed (id int GENERATED ALWAYS AS IDENTITY (START WITH 0))",
            (
                "22023".into(),
                "START value (0) cannot be less than MINVALUE (1)".into(),
            ),
        ),
        (
            "CREATE TABLE failed (id int GENERATED ALWAYS AS IDENTITY (MAXVALUE 3000000000))",
            (
                "22023".into(),
                "MAXVALUE (3000000000) is out of range for sequence data type integer".into(),
            ),
        ),
        (
            "CREATE TEMP TABLE failed (id int GENERATED ALWAYS AS IDENTITY (UNLOGGED))",
            (
                "42P16".into(),
                "cannot set logged status of a temporary sequence".into(),
            ),
        ),
        (
            "CREATE TABLE failed (id int GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME taken))",
            ("42P07".into(), "relation \"taken\" already exists".into()),
        ),
        (
            "CREATE TABLE failed (id int GENERATED ALWAYS AS IDENTITY (OWNED BY nope.col))",
            ("42P01".into(), "relation \"nope\" does not exist".into()),
        ),
        // The options are read when the sequence is created, after the statement has been analyzed; a repeated name or persistence is found during the analysis.
        (
            "CREATE TABLE failed (a int GENERATED ALWAYS AS IDENTITY (START 1 START 2), b nosuchtype)",
            ("42704".into(), "type \"nosuchtype\" does not exist".into()),
        ),
        (
            "CREATE TABLE failed (a int GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME q SEQUENCE NAME r), b nosuchtype)",
            conflicting(),
        ),
    ] {
        assert_eq!(error(&engine, statement), expected, "{statement}");
    }
    assert_eq!(
        rows(
            &engine,
            "SELECT count(*) AS n FROM pg_class WHERE relname IN ('failed', 'failed_id_seq', 'a', 'q')",
            &["n"]
        ),
        ["0"]
    );
}

#[test]
fn create_sequence_reads_its_options_as_postgresql_does() {
    let engine = Engine::new();
    run(
        &engine,
        "CREATE SEQUENCE restarted START WITH 5 RESTART WITH 9",
    );
    assert_eq!(
        rows(&engine, "SELECT nextval('restarted') AS n", &["n"]),
        ["9"]
    );
    assert_eq!(
        rows(
            &engine,
            "SELECT start_value FROM information_schema.sequences WHERE sequence_name = 'restarted'",
            &["start_value"]
        ),
        ["5"]
    );
    run(&engine, "CREATE SEQUENCE IF NOT EXISTS public.restarted");
    assert_eq!(
        engine.take_sql_notices(),
        [(
            "NOTICE".to_owned(),
            "relation \"restarted\" already exists, skipping".to_owned()
        )]
    );
    run(&engine, "CREATE SEQUENCE capped MAXVALUE 2");
    run(
        &engine,
        "SELECT nextval('capped'); SELECT nextval('capped')",
    );
    for (statement, expected) in [
        (
            "CREATE SEQUENCE public.restarted",
            ("42P07", "relation \"restarted\" already exists"),
        ),
        (
            "CREATE SEQUENCE failed START WITH 1.5",
            ("22P02", "invalid input syntax for type bigint: \"1.5\""),
        ),
        // `PostgreSQL` reads the bounds before the start, and the cache last.
        (
            "CREATE SEQUENCE failed START WITH 99999999999999999999 MAXVALUE 3000000000 AS integer",
            (
                "22023",
                "MAXVALUE (3000000000) is out of range for sequence data type integer",
            ),
        ),
        (
            "CREATE SEQUENCE failed CACHE 0 MAXVALUE 99999999999 AS integer",
            (
                "22023",
                "MAXVALUE (99999999999) is out of range for sequence data type integer",
            ),
        ),
        (
            "CREATE SEQUENCE failed START WITH 99999999999999999999",
            (
                "22003",
                "value \"99999999999999999999\" is out of range for type bigint",
            ),
        ),
        (
            "CREATE SEQUENCE failed RESTART WITH 0",
            (
                "22023",
                "RESTART value (0) cannot be less than MINVALUE (1)",
            ),
        ),
        (
            "CREATE SEQUENCE failed SEQUENCE NAME other",
            ("42601", "invalid sequence option SEQUENCE NAME"),
        ),
        (
            "CREATE SEQUENCE failed LOGGED",
            ("XX000", "option \"logged\" not recognized"),
        ),
        (
            "SELECT setval('capped', 5)",
            (
                "22003",
                "setval: value 5 is out of bounds for sequence \"capped\" (1..2)",
            ),
        ),
        (
            "SELECT nextval('capped')",
            (
                "2200H",
                "nextval: reached maximum value of sequence \"capped\" (2)",
            ),
        ),
    ] {
        assert_eq!(
            error(&engine, statement),
            (expected.0.to_owned(), expected.1.to_owned()),
            "{statement}"
        );
    }
}

#[test]
fn create_sequence_owned_by_names_a_column_or_none() {
    let engine = Engine::new();
    match engine.sql("CREATE SEQUENCE failed OWNED BY x", &[]) {
        Err(uqa_sql::SQLError::Diagnostic {
            sqlstate,
            message,
            hint,
            ..
        }) => assert_eq!(
            (sqlstate.as_str(), message.as_str(), hint.as_deref()),
            (
                "42601",
                "invalid OWNED BY option",
                Some("Specify OWNED BY table.column or OWNED BY NONE.")
            )
        ),
        other => panic!("expected the OWNED BY diagnostic, got {other:?}"),
    }
}

fn added_rows(engine: &Engine, label: &str) {
    assert_eq!(
        rows(
            engine,
            "SELECT v, s, id FROM filled ORDER BY v",
            &["v", "s", "id"]
        ),
        ["1|1|100", "2|2|101", "3|3|102"],
        "{label}"
    );
    assert_eq!(
        rows(engine, "SELECT v, id FROM emptied", &["v", "id"]),
        ["1|1"],
        "{label}"
    );
    assert_eq!(
        rows(
            engine,
            "SELECT pg_get_serial_sequence('filled', 'id') AS name",
            &["name"]
        ),
        ["public.filled_id_seq"],
        "{label}"
    );
}

#[test]
fn an_added_sequence_column_numbers_the_rows_its_table_holds() {
    on_every_engine(
        |engine, label| {
            run(
                engine,
                "CREATE TABLE filled (v int);
                 INSERT INTO filled VALUES (1), (2);
                 ALTER TABLE filled ADD COLUMN s serial;
                 ALTER TABLE filled ADD COLUMN id int GENERATED ALWAYS AS IDENTITY (START WITH 100);
                 INSERT INTO filled (v) VALUES (3);
                 CREATE TABLE emptied (v int);
                 ALTER TABLE emptied ADD COLUMN id int GENERATED BY DEFAULT AS IDENTITY;
                 INSERT INTO emptied (v) VALUES (1)",
            );
            added_rows(engine, label);
        },
        added_rows,
    );
    // An existing column fails before its sequence would be created, and the sequence never exists.
    let engine = Engine::new();
    run(&engine, "CREATE TABLE existing (id int, v int)");
    for statement in [
        "ALTER TABLE existing ADD COLUMN id int GENERATED ALWAYS AS IDENTITY (START 0)",
        "ALTER TABLE existing ADD COLUMN id serial",
    ] {
        assert_eq!(
            error(&engine, statement),
            (
                "42701".to_owned(),
                "column \"id\" of relation \"existing\" already exists".to_owned()
            ),
            "{statement}"
        );
    }
    run(
        &engine,
        "ALTER TABLE existing ADD COLUMN IF NOT EXISTS id serial",
    );
    assert_eq!(
        rows(
            &engine,
            "SELECT count(*) AS n FROM pg_class WHERE relname = 'existing_id_seq'",
            &["n"]
        ),
        ["0"]
    );
}

fn hierarchy_rows(engine: &Engine, label: &str) {
    for (query, columns, expected) in [
        (
            "SELECT k, id FROM parted ORDER BY k",
            &["k", "id"][..],
            vec!["1|100", "2|101", "3|102", "4|103"],
        ),
        (
            "SELECT pg_get_serial_sequence('parted_low', 'id') AS child, pg_get_serial_sequence('parted', 'id') AS parent",
            &["child", "parent"],
            vec!["null|public.parted_id_seq"],
        ),
        ("SELECT v, s FROM serial_child", &["v", "s"], vec!["1|1"]),
        (
            "SELECT relname FROM pg_class WHERE relkind = 'S' ORDER BY relname",
            &["relname"],
            vec!["parted_id_seq", "serial_parent_s_seq"],
        ),
    ] {
        assert_eq!(rows(engine, query, columns), expected, "{label}: {query}");
    }
}

#[test]
fn an_added_sequence_column_reaches_child_tables_as_postgresql_does() {
    on_every_engine(
        |engine, label| {
            // Partitions draw from their parent's identity sequence.
            run(
                engine,
                "CREATE TABLE parted (k int) PARTITION BY RANGE (k);
                 CREATE TABLE parted_low PARTITION OF parted FOR VALUES FROM (0) TO (10);
                 INSERT INTO parted VALUES (1), (2);
                 ALTER TABLE parted ADD COLUMN id int GENERATED ALWAYS AS IDENTITY (START WITH 100);
                 INSERT INTO parted_low (k) VALUES (3);
                 INSERT INTO parted (k) VALUES (4)",
            );
            // Identity is not inherited, so an inheritance parent cannot take an identity column, while its children take the default of a `SERIAL` one.
            run(
                engine,
                "CREATE TABLE identity_parent (v int);
                 CREATE TABLE identity_child () INHERITS (identity_parent);
                 CREATE TABLE serial_parent (v int);
                 CREATE TABLE serial_child () INHERITS (serial_parent);
                 INSERT INTO serial_child VALUES (1);
                 ALTER TABLE serial_parent ADD COLUMN s serial",
            );
            assert_eq!(
                error(
                    engine,
                    "ALTER TABLE identity_parent ADD COLUMN id int GENERATED ALWAYS AS IDENTITY"
                ),
                (
                    "42P16".to_owned(),
                    "cannot recursively add identity column to table that has child tables"
                        .to_owned()
                ),
                "{label}"
            );
            hierarchy_rows(engine, label);
        },
        hierarchy_rows,
    );
}
