//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! The `ALTER TABLE ... ALTER COLUMN` identity actions change an identity column as `PostgreSQL` does: `ADD GENERATED` gives a `NOT NULL` column without a default its own sequence, `SET GENERATED`, `RESTART` and `SET` change its generation and sequence, and `DROP IDENTITY` drops the sequence and keeps the `NOT NULL`. A partitioned table's partitions share its sequence and follow each change. The expected values and errors are those of `PostgreSQL` 18.4.

use super::*;

/// Run `scenario` on a memory engine and on each persistent layout, then `reopened` on each layout after the engine that ran the scenario closed.
fn on_every_engine(scenario: impl Fn(&Engine, &str), reopened: impl Fn(&Engine, &str)) {
    scenario(&Engine::new(), "memory");
    for layout in LAYOUTS {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("identity-alterations.db");
        let label = format!("{layout:?}");
        scenario(&open(layout, &path), &label);
        reopened(&open(layout, &path), &label);
    }
}

/// The SQLSTATE and message of the error `statement` fails with.
fn error(engine: &Engine, statement: &str) -> (String, String) {
    let error = engine
        .sql(statement, &[])
        .expect_err(&format!("{statement} must fail"));
    (
        error.sqlstate().unwrap_or_default().to_owned(),
        error.to_string(),
    )
}

fn assert_errors(engine: &Engine, label: &str, cases: &[(&str, &str, &str)]) {
    for (statement, sqlstate, message) in cases {
        assert_eq!(
            error(engine, statement),
            ((*sqlstate).to_owned(), (*message).to_owned()),
            "{label}: {statement}"
        );
    }
}

fn altered_rows(engine: &Engine, label: &str) {
    for (query, columns, expected) in [
        (
            "SELECT id, v FROM changed ORDER BY v",
            &["id", "v"][..],
            vec!["1|1", "2|2", "100|3", "110|4", "1|5", "500|6", "7|7"],
        ),
        (
            "SELECT identity_generation, identity_start, identity_increment, identity_maximum FROM information_schema.columns WHERE table_name = 'changed' AND column_name = 'id'",
            &[
                "identity_generation",
                "identity_start",
                "identity_increment",
                "identity_maximum",
            ],
            vec!["ALWAYS|1|1|32767"],
        ),
        (
            "SELECT id, v FROM added ORDER BY v",
            &["id", "v"],
            vec!["1|1", "2|2"],
        ),
        (
            "SELECT pg_get_serial_sequence('added', 'id') AS name",
            &["name"],
            vec!["public.added_ids"],
        ),
        (
            "SELECT is_identity, is_nullable FROM information_schema.columns WHERE table_name = 'dropped' AND column_name = 'id'",
            &["is_identity", "is_nullable"],
            vec!["NO|NO"],
        ),
        (
            "SELECT count(*) AS n FROM pg_class WHERE relname = 'dropped_id_seq'",
            &["n"],
            vec!["0"],
        ),
    ] {
        assert_eq!(rows(engine, query, columns), expected, "{label}: {query}");
    }
}

#[test]
fn identity_actions_change_the_column_and_its_sequence() {
    on_every_engine(
        |engine, label| {
            run(
                engine,
                "CREATE TABLE changed (id int GENERATED ALWAYS AS IDENTITY, v int);
                 INSERT INTO changed (v) VALUES (1), (2);
                 ALTER TABLE changed ALTER COLUMN id RESTART WITH 100;
                 INSERT INTO changed (v) VALUES (3);
                 ALTER TABLE changed ALTER COLUMN id SET INCREMENT BY 10;
                 INSERT INTO changed (v) VALUES (4);
                 ALTER TABLE changed ALTER COLUMN id RESTART;
                 INSERT INTO changed (v) VALUES (5);
                 ALTER TABLE changed ALTER COLUMN id SET GENERATED BY DEFAULT;
                 INSERT INTO changed VALUES (500, 6);
                 ALTER TABLE changed ALTER COLUMN id SET GENERATED ALWAYS SET INCREMENT BY 1 RESTART WITH 7;
                 INSERT INTO changed (v) VALUES (7);
                 ALTER TABLE changed ALTER COLUMN id TYPE smallint;
                 CREATE TABLE added (id int, v int);
                 INSERT INTO added VALUES (1, 1);
                 ALTER TABLE added ALTER COLUMN id SET NOT NULL;
                 ALTER TABLE added ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME added_ids START WITH 2);
                 INSERT INTO added (v) VALUES (2);
                 CREATE TABLE dropped (id int GENERATED ALWAYS AS IDENTITY, v int);
                 ALTER TABLE dropped ALTER COLUMN id DROP IDENTITY",
            );
            assert_eq!(
                error(engine, "INSERT INTO changed VALUES (8, 8)").0,
                "428C9",
                "{label}"
            );
            assert_eq!(
                error(engine, "INSERT INTO dropped (v) VALUES (1)").0,
                "23502",
                "{label}"
            );
            altered_rows(engine, label);
        },
        altered_rows,
    );
}

#[test]
fn identity_actions_fail_as_postgresql_does() {
    let engine = Engine::new();
    run(
        &engine,
        "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY, v int, n int NOT NULL, d int NOT NULL DEFAULT 5, s serial, words text NOT NULL, g int NOT NULL GENERATED ALWAYS AS (v * 2) STORED)",
    );
    assert_errors(
        &engine,
        "memory",
        &[
            // The column comes first, then the sequence options, which only an identity column reads, then the generation and the column itself.
            ("ALTER TABLE t ALTER COLUMN nope SET START 99999999999999999999", "42703", "column \"nope\" of relation \"t\" does not exist"),
            ("ALTER TABLE t ALTER COLUMN v SET START 99999999999999999999", "55000", "column \"v\" of relation \"t\" is not an identity column"),
            ("ALTER TABLE t ALTER COLUMN v RESTART", "55000", "column \"v\" of relation \"t\" is not an identity column"),
            ("ALTER TABLE t ALTER COLUMN id SET START 3 SET START 4", "42601", "conflicting or redundant options"),
            ("ALTER TABLE t ALTER COLUMN id SET MAXVALUE 0 SET START 99999999999999999999", "22023", "MINVALUE (1) must be less than MAXVALUE (0)"),
            ("ALTER TABLE t ALTER COLUMN id SET GENERATED BY DEFAULT SET GENERATED ALWAYS RESTART 0", "22023", "RESTART value (0) cannot be less than MINVALUE (1)"),
            ("ALTER TABLE t ALTER COLUMN id SET GENERATED ALWAYS SET GENERATED BY DEFAULT", "42601", "conflicting or redundant options"),
            ("ALTER TABLE t ALTER COLUMN id SET SEQUENCE NAME other", "42601", "invalid sequence option SEQUENCE NAME"),
            ("ALTER TABLE t ALTER COLUMN id SET LOGGED", "XX000", "option \"logged\" not recognized"),
            ("ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY", "55000", "column \"id\" of relation \"t\" is already an identity column"),
            ("ALTER TABLE t ALTER COLUMN v ADD GENERATED ALWAYS AS IDENTITY", "55000", "column \"v\" of relation \"t\" must be declared NOT NULL before identity can be added"),
            ("ALTER TABLE t ALTER COLUMN d ADD GENERATED ALWAYS AS IDENTITY", "55000", "column \"d\" of relation \"t\" already has a default value"),
            ("ALTER TABLE t ALTER COLUMN s ADD GENERATED ALWAYS AS IDENTITY", "55000", "column \"s\" of relation \"t\" already has a default value"),
            ("ALTER TABLE t ALTER COLUMN g ADD GENERATED ALWAYS AS IDENTITY", "55000", "column \"g\" of relation \"t\" already has a default value"),
            ("ALTER TABLE t ALTER COLUMN words ADD GENERATED ALWAYS AS IDENTITY", "22023", "identity column type must be smallint, integer, or bigint"),
            ("ALTER TABLE t ALTER COLUMN nope ADD GENERATED ALWAYS AS IDENTITY", "42703", "column \"nope\" of relation \"t\" does not exist"),
            ("ALTER TABLE t ALTER COLUMN v DROP IDENTITY", "55000", "column \"v\" of relation \"t\" is not an identity column"),
            ("ALTER TABLE t ALTER COLUMN nope DROP IDENTITY IF EXISTS", "42703", "column \"nope\" of relation \"t\" does not exist"),
            ("ALTER TABLE t ALTER COLUMN id SET DEFAULT 5", "42601", "column \"id\" of relation \"t\" is an identity column"),
            ("ALTER TABLE t ALTER COLUMN id TYPE text", "22023", "identity column type must be smallint, integer, or bigint"),
        ],
    );
    run(&engine, "ALTER TABLE t ALTER COLUMN id RESTART WITH 40000");
    assert_errors(
        &engine,
        "memory",
        &[(
            "ALTER TABLE t ALTER COLUMN id TYPE smallint",
            "22023",
            "RESTART value (40000) cannot be greater than MAXVALUE (32767)",
        )],
    );
    run(
        &engine,
        "ALTER TABLE t ALTER COLUMN v DROP IDENTITY IF EXISTS",
    );
    assert_eq!(
        engine.take_sql_notices(),
        [uqa_engine::SQLNotice::notice(
            "column \"v\" of relation \"t\" is not an identity column, skipping"
        )]
    );
    for (statement, message, hint) in [
        (
            "ALTER TABLE t ALTER COLUMN id DROP DEFAULT",
            "column \"id\" of relation \"t\" is an identity column",
            Some("Use ALTER TABLE ... ALTER COLUMN ... DROP IDENTITY instead."),
        ),
        (
            "ALTER TABLE t ALTER COLUMN g SET DEFAULT 5",
            "column \"g\" of relation \"t\" is a generated column",
            Some("Use ALTER TABLE ... ALTER COLUMN ... SET EXPRESSION instead."),
        ),
        (
            "ALTER TABLE t ALTER COLUMN g DROP DEFAULT",
            "column \"g\" of relation \"t\" is a generated column",
            Some("Use ALTER TABLE ... ALTER COLUMN ... DROP EXPRESSION instead."),
        ),
    ] {
        match engine.sql(statement, &[]) {
            Err(uqa_sql::SQLError::Diagnostic {
                sqlstate,
                message: actual,
                hint: actual_hint,
                ..
            }) => assert_eq!(
                (sqlstate.as_str(), actual.as_str(), actual_hint.as_deref()),
                ("42601", message, hint),
                "{statement}"
            ),
            other => panic!("{statement}: expected a diagnostic, got {other:?}"),
        }
    }
}

fn partitioned_rows(engine: &Engine, label: &str) {
    for (query, columns, expected) in [
        (
            "SELECT id, k FROM parted ORDER BY k",
            &["id", "k"][..],
            vec!["10|1", "11|2", "50|3"],
        ),
        (
            "SELECT table_name, is_identity FROM information_schema.columns WHERE table_name IN ('parted', 'parted_low') AND column_name = 'id' ORDER BY table_name",
            &["table_name", "is_identity"],
            vec!["parted|NO", "parted_low|NO"],
        ),
        (
            "SELECT count(*) AS n FROM pg_class WHERE relkind = 'S'",
            &["n"],
            vec!["0"],
        ),
    ] {
        assert_eq!(rows(engine, query, columns), expected, "{label}: {query}");
    }
}

#[test]
fn a_partitioned_tables_identity_actions_reach_its_partitions() {
    on_every_engine(
        |engine, label| {
            run(
                engine,
                "CREATE TABLE parted (id int NOT NULL, k int) PARTITION BY RANGE (k);
                 CREATE TABLE parted_low PARTITION OF parted FOR VALUES FROM (0) TO (10)",
            );
            let only = |message: &str| ("42P16".to_owned(), message.to_owned());
            for (statement, expected) in [
                (
                    "ALTER TABLE ONLY parted ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY",
                    only("cannot add identity to a column of only the partitioned table"),
                ),
                (
                    "ALTER TABLE parted_low ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY",
                    only("cannot add identity to a column of a partition"),
                ),
            ] {
                assert_eq!(error(engine, statement), expected, "{label}: {statement}");
            }
            run(
                engine,
                "ALTER TABLE parted ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (START WITH 10);
                 INSERT INTO parted (k) VALUES (1);
                 INSERT INTO parted_low (k) VALUES (2)",
            );
            for (statement, expected) in [
                (
                    "ALTER TABLE parted_low ALTER COLUMN id SET GENERATED BY DEFAULT",
                    only("cannot change identity column of a partition"),
                ),
                (
                    "ALTER TABLE ONLY parted ALTER COLUMN id SET GENERATED BY DEFAULT",
                    only("cannot change identity column of only the partitioned table"),
                ),
            ] {
                assert_eq!(error(engine, statement), expected, "{label}: {statement}");
            }
            run(
                engine,
                "ALTER TABLE parted ALTER COLUMN id SET GENERATED BY DEFAULT;
                 ALTER TABLE parted ALTER COLUMN id RESTART WITH 50;
                 INSERT INTO parted_low (k) VALUES (3)",
            );
            assert_eq!(
                rows(
                    engine,
                    "SELECT table_name, identity_generation FROM information_schema.columns WHERE table_name IN ('parted', 'parted_low') AND column_name = 'id' ORDER BY table_name",
                    &["table_name", "identity_generation"]
                ),
                ["parted|BY DEFAULT", "parted_low|BY DEFAULT"],
                "{label}"
            );
            for (statement, expected) in [
                (
                    "ALTER TABLE parted_low ALTER COLUMN id DROP IDENTITY",
                    only("cannot drop identity from a column of a partition"),
                ),
                (
                    "ALTER TABLE ONLY parted ALTER COLUMN id DROP IDENTITY",
                    only("cannot drop identity from a column of only the partitioned table"),
                ),
            ] {
                assert_eq!(error(engine, statement), expected, "{label}: {statement}");
            }
            run(engine, "ALTER TABLE parted ALTER COLUMN id DROP IDENTITY");
            partitioned_rows(engine, label);
        },
        partitioned_rows,
    );
}

#[test]
fn an_identity_sequence_resists_a_direct_drop_and_another_owner() {
    let engine = Engine::new();
    run(
        &engine,
        "CREATE TABLE t (id int GENERATED ALWAYS AS IDENTITY);
         CREATE SCHEMA other;
         CREATE TABLE other.o (id int GENERATED ALWAYS AS IDENTITY);
         CREATE TABLE \"Mixed\" (\"Col\" int GENERATED ALWAYS AS IDENTITY)",
    );
    // Objects are named as the search path shows them: by their own name when it finds them, quoted as identifiers need.
    for (statement, sqlstate, message, detail, hint) in [
        (
            "DROP SEQUENCE t_id_seq",
            "2BP01",
            "cannot drop sequence t_id_seq because column id of table t requires it",
            None,
            Some("You can drop column id of table t instead."),
        ),
        (
            "DROP SEQUENCE other.o_id_seq",
            "2BP01",
            "cannot drop sequence other.o_id_seq because column id of table other.o requires it",
            None,
            Some("You can drop column id of table other.o instead."),
        ),
        (
            "DROP SEQUENCE \"Mixed_Col_seq\"",
            "2BP01",
            "cannot drop sequence \"Mixed_Col_seq\" because column Col of table \"Mixed\" requires it",
            None,
            Some("You can drop column Col of table \"Mixed\" instead."),
        ),
        (
            "ALTER SEQUENCE t_id_seq OWNED BY NONE",
            "0A000",
            "cannot change ownership of identity sequence",
            Some("Sequence \"t_id_seq\" is linked to table \"t\"."),
            None,
        ),
    ] {
        match engine.sql(statement, &[]) {
            Err(uqa_sql::SQLError::Diagnostic {
                sqlstate: actual_state,
                message: actual_message,
                detail: actual_detail,
                hint: actual_hint,
            }) => assert_eq!(
                (
                    actual_state.as_str(),
                    actual_message.as_str(),
                    actual_detail.as_deref(),
                    actual_hint.as_deref()
                ),
                (sqlstate, message, detail, hint),
                "{statement}"
            ),
            other => panic!("{statement}: expected a diagnostic, got {other:?}"),
        }
    }
}
