//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! A SERIAL or identity column that is not its table's single primary key is an ordinary column with a sequence default, so `PostgreSQL` keeps every row that supplies a value another row holds. Only the key names a row's physical document. The expected rows are those of `PostgreSQL` 18.4.

use super::*;

/// Run `scenario` on a memory engine and on each persistent layout, then `reopened` on each layout after the engine that ran the scenario closed.
fn on_every_engine(scenario: impl Fn(&Engine, &str), reopened: impl Fn(&Engine, &str)) {
    scenario(&Engine::new(), "memory");
    for layout in LAYOUTS {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("sequence-columns.db");
        let label = format!("{layout:?}");
        scenario(&open(layout, &path), &label);
        reopened(&open(layout, &path), &label);
    }
}

fn command_tag(engine: &Engine, statement: &str) -> String {
    engine
        .sql(statement, &[])
        .unwrap_or_else(|error| panic!("{statement}: {error}"))
        .command_tag
        .unwrap_or_else(|| panic!("{statement}: no command tag"))
}

fn sequence_rows(engine: &Engine, label: &str) {
    assert_eq!(
        rows(
            engine,
            "SELECT id, v FROM serial_rows ORDER BY v",
            &["id", "v"]
        ),
        ["1|1", "1|2"],
        "{label}"
    );
    assert_eq!(
        rows(engine, "SELECT count(*) AS n FROM identity_rows", &["n"]),
        ["0"],
        "{label}"
    );
    assert_eq!(
        rows(
            engine,
            "SELECT id, v FROM moved_rows ORDER BY v",
            &["id", "v"]
        ),
        ["2|1", "2|2"],
        "{label}"
    );
    assert_eq!(
        rows(
            engine,
            "SELECT a, b, v FROM two_serials ORDER BY v",
            &["a", "b", "v"]
        ),
        ["1|1|1", "1|2|2", "2|1|3"],
        "{label}"
    );
    assert_eq!(
        rows(
            engine,
            "SELECT id, v FROM reused_rows ORDER BY v",
            &["id", "v"]
        ),
        ["1|1", "2|4", "3|13", "3|15"],
        "{label}"
    );
}

#[test]
fn rows_that_supply_a_sequence_value_another_row_holds_are_all_kept() {
    on_every_engine(
        |engine, label| {
            run(engine, "CREATE TABLE serial_rows (id serial, v integer)");
            run(engine, "INSERT INTO serial_rows (v) VALUES (1)");
            run(engine, "INSERT INTO serial_rows (id, v) VALUES (1, 2)");

            run(
                engine,
                "CREATE TABLE identity_rows (id integer GENERATED BY DEFAULT AS IDENTITY, v integer)",
            );
            run(engine, "INSERT INTO identity_rows (v) VALUES (1)");
            run(engine, "INSERT INTO identity_rows (id, v) VALUES (1, 2)");
            assert_eq!(
                rows(
                    engine,
                    "SELECT id, v FROM identity_rows ORDER BY v",
                    &["id", "v"]
                ),
                ["1|1", "1|2"],
                "{label}"
            );
            assert_eq!(
                command_tag(engine, "UPDATE identity_rows SET v = 3 WHERE id = 1"),
                "UPDATE 2",
                "{label}"
            );
            assert_eq!(
                command_tag(engine, "DELETE FROM identity_rows WHERE v = 3 AND id = 1"),
                "DELETE 2",
                "{label}"
            );

            run(engine, "CREATE TABLE moved_rows (id serial, v integer)");
            run(engine, "INSERT INTO moved_rows (v) VALUES (1), (2)");
            run(engine, "UPDATE moved_rows SET id = 2 WHERE v = 1");

            run(
                engine,
                "CREATE TABLE two_serials (a serial, b serial, v integer)",
            );
            run(engine, "INSERT INTO two_serials (v) VALUES (1)");
            run(engine, "INSERT INTO two_serials (a, v) VALUES (1, 2)");
            run(engine, "INSERT INTO two_serials (b, v) VALUES (1, 3)");

            run(engine, "CREATE TABLE reused_rows (id serial, v integer)");
            run(engine, "INSERT INTO reused_rows (v) VALUES (1), (2), (3)");
            run(engine, "DELETE FROM reused_rows WHERE id = 2");
            run(
                engine,
                "INSERT INTO reused_rows (id, v) VALUES (2, 4), (3, 5)",
            );
            assert_eq!(
                rows(
                    engine,
                    "SELECT id, v FROM reused_rows ORDER BY v",
                    &["id", "v"]
                ),
                ["1|1", "3|3", "2|4", "3|5"],
                "{label}"
            );
            assert_eq!(
                command_tag(engine, "UPDATE reused_rows SET v = v + 10 WHERE id = 3"),
                "UPDATE 2",
                "{label}"
            );
            sequence_rows(engine, label);
        },
        sequence_rows,
    );
}

fn source_rows(engine: &Engine, label: &str) {
    assert_eq!(
        rows(
            engine,
            "SELECT id, v FROM merged_rows ORDER BY v",
            &["id", "v"]
        ),
        ["1|1", "1|5", "1|9"],
        "{label}"
    );
    assert_eq!(
        rows(
            engine,
            "SELECT id, v FROM triggered_rows ORDER BY v",
            &["id", "v"]
        ),
        ["1|1", "1|2"],
        "{label}"
    );
    assert_eq!(
        rows(
            engine,
            "SELECT id, k FROM partitioned_rows ORDER BY k",
            &["id", "k"]
        ),
        ["1|1", "1|2"],
        "{label}"
    );
    assert_eq!(
        rows(
            engine,
            "SELECT id, k, v FROM conflict_rows ORDER BY k",
            &["id", "k", "v"]
        ),
        ["1|1|9", "1|2|2"],
        "{label}"
    );
}

#[test]
fn every_insert_source_keeps_rows_that_supply_a_sequence_value_another_row_holds() {
    on_every_engine(
        |engine, label| {
            run(engine, "CREATE TABLE merged_rows (id serial, v integer)");
            run(engine, "INSERT INTO merged_rows (v) VALUES (1)");
            run(
                engine,
                "MERGE INTO merged_rows USING (VALUES (1, 5)) AS source(id, v) ON false
                 WHEN NOT MATCHED THEN INSERT (id, v) VALUES (source.id, source.v)",
            );
            run(engine, "INSERT INTO merged_rows (id, v) SELECT 1, 9");

            run(engine, "CREATE TABLE triggered_rows (id serial, v integer)");
            run(
                engine,
                "CREATE FUNCTION first_triggered_id() RETURNS trigger LANGUAGE plpgsql AS $$
                 BEGIN NEW.id := 1; RETURN NEW; END $$",
            );
            run(engine, "INSERT INTO triggered_rows (v) VALUES (1)");
            run(
                engine,
                "CREATE TRIGGER first_triggered_id BEFORE INSERT ON triggered_rows
                 FOR EACH ROW EXECUTE FUNCTION first_triggered_id()",
            );
            run(engine, "INSERT INTO triggered_rows (v) VALUES (2)");

            run(
                engine,
                "CREATE TABLE partitioned_rows (id serial, k integer) PARTITION BY RANGE (k);
                 CREATE TABLE partitioned_rows_low PARTITION OF partitioned_rows FOR VALUES FROM (0) TO (100)",
            );
            run(engine, "INSERT INTO partitioned_rows (k) VALUES (1)");
            run(engine, "INSERT INTO partitioned_rows (id, k) VALUES (1, 2)");

            run(
                engine,
                "CREATE TABLE conflict_rows (id serial, k integer UNIQUE, v integer)",
            );
            run(engine, "INSERT INTO conflict_rows (k, v) VALUES (1, 1)");
            run(
                engine,
                "INSERT INTO conflict_rows (id, k, v) VALUES (1, 2, 2)
                 ON CONFLICT (k) DO UPDATE SET v = excluded.v",
            );
            run(
                engine,
                "INSERT INTO conflict_rows (id, k, v) VALUES (7, 1, 9)
                 ON CONFLICT (k) DO UPDATE SET v = excluded.v",
            );
            source_rows(engine, label);
        },
        source_rows,
    );
}

fn keyed_rows(engine: &Engine, label: &str) {
    assert_eq!(
        rows(
            engine,
            "SELECT id, k, v FROM keyed_rows ORDER BY v",
            &["id", "k", "v"]
        ),
        ["1|30|1", "1|1|2"],
        "{label}"
    );
    assert_eq!(
        rows(engine, "SELECT v FROM keyed_rows WHERE k = 1", &["v"]),
        ["2"],
        "{label}"
    );
    assert!(
        rows(engine, "SELECT v FROM keyed_rows WHERE k = 20", &["v"]).is_empty(),
        "{label}"
    );
    assert_eq!(
        state(engine, "INSERT INTO keyed_rows (k, v) VALUES (30, 3)").as_deref(),
        Some("23505"),
        "{label}"
    );
    assert_eq!(
        rows(
            engine,
            "SELECT a, id, v FROM keyed_identity ORDER BY v",
            &["a", "id", "v"]
        ),
        ["1|1|1", "3|2|3"],
        "{label}"
    );
}

#[test]
fn the_primary_key_names_the_rows_of_a_table_with_a_sequence_column_beside_it() {
    on_every_engine(
        |engine, label| {
            run(
                engine,
                "CREATE TABLE keyed_rows (id serial, k integer PRIMARY KEY, v integer)",
            );
            run(engine, "INSERT INTO keyed_rows (k, v) VALUES (10, 1)");
            run(
                engine,
                "INSERT INTO keyed_rows (id, k, v) VALUES (1, 20, 2)",
            );
            assert_eq!(
                command_tag(engine, "UPDATE keyed_rows SET k = 30 WHERE k = 10"),
                "UPDATE 1",
                "{label}"
            );
            assert_eq!(
                command_tag(engine, "UPDATE keyed_rows SET k = 1 WHERE k = 20"),
                "UPDATE 1",
                "{label}"
            );

            run(
                engine,
                "CREATE TABLE keyed_identity (a serial, id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v integer)",
            );
            run(engine, "INSERT INTO keyed_identity (id, v) VALUES (1, 1)");
            assert_eq!(
                state(engine, "INSERT INTO keyed_identity (v) VALUES (2)").as_deref(),
                Some("23505"),
                "{label}"
            );
            run(engine, "INSERT INTO keyed_identity (v) VALUES (3)");
            keyed_rows(engine, label);
        },
        keyed_rows,
    );
}
