#!/usr/bin/env python3
#
# Unified Query Algebra
#
# Copyright (c) 2023-2026 Cognica, Inc.
#

"""Package the existing portable notification modules as a browser ES module."""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import re
import shutil


ROOT = pathlib.Path(__file__).resolve().parents[1]
MODULES = (
    "http-error.js",
    "http-json.js",
    "notification-bytes.js",
    "notification-error.js",
    "notification-request.js",
    "notification-framing.js",
    "notification-protocol.js",
    "notification-queue.js",
    "notification-headers.js",
    "notification-subscription.js",
    "notification-stream.js",
)
EXPORTS = {
    "notification-error.js": "NotificationError, NotificationEvent, protocol, cancelled, timeout",
    "notification-request.js": "MAX_WIRE_BYTES",
    "notification-stream.js": "runStream",
    "notification-subscription.js": "subscribe, HttpNotificationSubscription",
}


def bundle() -> str:
    sources = {name: (ROOT / "crates/uqa-node" / name).read_text() for name in MODULES}
    for name, source in sources.items():
        dependencies = re.findall(r'\brequire\("([^"]+)"\)', source)
        if any(not dependency.startswith("./") or dependency[2:] not in sources
               for dependency in dependencies):
            raise ValueError(f"Nonportable dependency in {name}")
    parts = [
        "// Generated by scripts/build-browser-notifications.py; edit the owning modules.\n",
        "const factories = Object.create(null);\nconst instances = Object.create(null);\n",
        "function require(name) {\n"
        "  if (!Object.hasOwn(instances, name)) {\n"
        "    const module = { exports: {} };\n"
        "    instances[name] = module;\n"
        "    factories[name](module, require);\n"
        "  }\n"
        "  return instances[name].exports;\n"
        "}\n",
    ]
    for name, source in sources.items():
        digest = hashlib.sha256(source.encode()).hexdigest()
        parts.append(f'\n// {name} sha256:{digest}\n')
        parts.append(f'factories["./{name}"] = (module, require) => {{\n{source}\n}};\n')
    for name, names in EXPORTS.items():
        parts.append(f'\nconst {{ {names} }} = require("./{name}");\nexport {{ {names} }};\n')
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path,
                        default=ROOT / "crates/uqa-wasm/js/notification-core.mjs")
    args = parser.parse_args()
    output = bundle()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output)
    args.output.with_name("notifications.d.ts").write_bytes(
        (ROOT / "crates/uqa-node/notifications.d.ts").read_bytes())
    transport = ROOT / "crates/uqa-wasm/js/notification-fetch.mjs"
    destination = args.output.with_name(transport.name)
    if destination.resolve() != transport.resolve():
        shutil.copyfile(transport, destination)
    print(f"Packaged {len(MODULES)} portable modules into {args.output}")


if __name__ == "__main__":
    main()
