//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! `PostgreSQL` catalog definition function identities.

use super::BuiltinRoutineCatalogEntry;

pub const ROUTINES: &[BuiltinRoutineCatalogEntry] = &[
    BuiltinRoutineCatalogEntry {
        oid: 1640,
        name: "pg_get_viewdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "r",
        leakproof: false,
        return_type: 25,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_viewdef_name",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1641,
        name: "pg_get_viewdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "r",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_viewdef",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2505,
        name: "pg_get_viewdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "r",
        leakproof: false,
        return_type: 25,
        argument_types: &[25, 16],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_viewdef_name_ext",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2506,
        name: "pg_get_viewdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "r",
        leakproof: false,
        return_type: 25,
        argument_types: &[26, 16],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_viewdef_ext",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3159,
        name: "pg_get_viewdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "r",
        leakproof: false,
        return_type: 25,
        argument_types: &[26, 23],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_viewdef_wrap",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1387,
        name: "pg_get_constraintdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_constraintdef",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2508,
        name: "pg_get_constraintdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26, 16],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_constraintdef_ext",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2162,
        name: "pg_get_function_arguments",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_function_arguments",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2232,
        name: "pg_get_function_identity_arguments",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_function_identity_arguments",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2165,
        name: "pg_get_function_result",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_function_result",
    },
    BuiltinRoutineCatalogEntry {
        oid: 9704,
        name: "pg_get_function_sqlbody",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_function_sqlbody",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1643,
        name: "pg_get_indexdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_indexdef",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2507,
        name: "pg_get_indexdef",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26, 23, 16],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_get_indexdef_ext",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1081,
        name: "format_type",
        kind: "f",
        strict: false,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26, 23],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "format_type",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3537,
        name: "pg_describe_object",
        kind: "f",
        strict: true,
        volatility: "s",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[26, 26, 23],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "pg_describe_object",
    },
];
