[package]
name = "uqa-storage-redb"
description = "redb physical KeyValue storage provider for UQA"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
rust-version.workspace = true
documentation = "https://docs.rs/uqa-storage-redb"
exclude.workspace = true

[dependencies]
uqa-storage = { workspace = true }
parking_lot = { workspace = true }
redb = { workspace = true }

[dev-dependencies]
tempfile = "3.13"
uqa-analysis = { workspace = true }

[lints]
workspace = true
