//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! `PostgreSQL` 18 built-in routine metadata exposed through the virtual catalogs.

#[derive(Debug, Clone, Copy)]
pub(super) struct BuiltinRoutineCatalogEntry {
    pub(super) oid: i64,
    pub(super) name: &'static str,
    pub(super) kind: &'static str,
    pub(super) strict: bool,
    pub(super) volatility: &'static str,
    pub(super) leakproof: bool,
    pub(super) return_type: i64,
    pub(super) argument_types: &'static [i64],
    pub(super) argument_names: &'static [&'static str],
    pub(super) default_arguments: usize,
    pub(super) argument_defaults: Option<&'static str>,
    pub(super) source: &'static str,
}

const FALSE_NODE: &str = "({CONST :consttype 16 :consttypmod -1 :constcollid 0 :constlen 1 :constbyval true :constisnull false :location -1 :constvalue 1 [ 0 0 0 0 0 0 0 0 ]})";

pub(super) const PG18_BUILTIN_ROUTINES: &[BuiltinRoutineCatalogEntry] = &[
    BuiltinRoutineCatalogEntry {
        oid: 6381,
        name: "array_reverse",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_reverse",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6388,
        name: "array_sort",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_sort",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6389,
        name: "array_sort",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277, 16],
        argument_names: &["array", "descending"],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_sort_order",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6390,
        name: "array_sort",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277, 16, 16],
        argument_names: &["array", "descending", "nulls_first"],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_sort_order_nulls_first",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6412,
        name: "casefold",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 25,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "casefold",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6364,
        name: "crc32",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: true,
        return_type: 20,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "crc32_bytea",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6365,
        name: "crc32c",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: true,
        return_type: 20,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "crc32c_bytea",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6383,
        name: "gamma",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 701,
        argument_types: &[701],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "dgamma",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6384,
        name: "lgamma",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 701,
        argument_types: &[701],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "dlgamma",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3261,
        name: "json_strip_nulls",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 114,
        argument_types: &[114, 16],
        argument_names: &["target", "strip_in_arrays"],
        default_arguments: 1,
        argument_defaults: Some(FALSE_NODE),
        source: "json_strip_nulls",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3262,
        name: "jsonb_strip_nulls",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 3802,
        argument_types: &[3802, 16],
        argument_names: &["target", "strip_in_arrays"],
        default_arguments: 1,
        argument_defaults: Some(FALSE_NODE),
        source: "jsonb_strip_nulls",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2050,
        name: "max",
        kind: "a",
        strict: false,
        volatility: "i",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6373,
        name: "max",
        kind: "a",
        strict: false,
        volatility: "i",
        leakproof: false,
        return_type: 2249,
        argument_types: &[2249],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6395,
        name: "max",
        kind: "a",
        strict: false,
        volatility: "i",
        leakproof: false,
        return_type: 17,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2051,
        name: "min",
        kind: "a",
        strict: false,
        volatility: "i",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6374,
        name: "min",
        kind: "a",
        strict: false,
        volatility: "i",
        leakproof: false,
        return_type: 2249,
        argument_types: &[2249],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6396,
        name: "min",
        kind: "a",
        strict: false,
        volatility: "i",
        leakproof: false,
        return_type: 17,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6382,
        name: "reverse",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 17,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "bytea_reverse",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3062,
        name: "reverse",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 25,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "text_reverse",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6330,
        name: "to_bin",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 25,
        argument_types: &[23],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_bin32",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6331,
        name: "to_bin",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 25,
        argument_types: &[20],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_bin64",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6332,
        name: "to_oct",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 25,
        argument_types: &[23],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_oct32",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6333,
        name: "to_oct",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 25,
        argument_types: &[20],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_oct64",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6342,
        name: "uuid_extract_timestamp",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 1184,
        argument_types: &[2950],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "uuid_extract_timestamp",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6343,
        name: "uuid_extract_version",
        kind: "f",
        strict: true,
        volatility: "i",
        leakproof: false,
        return_type: 21,
        argument_types: &[2950],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "uuid_extract_version",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6428,
        name: "uuidv4",
        kind: "f",
        strict: true,
        volatility: "v",
        leakproof: false,
        return_type: 2950,
        argument_types: &[],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "gen_random_uuid",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6429,
        name: "uuidv7",
        kind: "f",
        strict: true,
        volatility: "v",
        leakproof: false,
        return_type: 2950,
        argument_types: &[],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "uuidv7",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6430,
        name: "uuidv7",
        kind: "f",
        strict: true,
        volatility: "v",
        leakproof: false,
        return_type: 2950,
        argument_types: &[1186],
        argument_names: &["shift"],
        default_arguments: 0,
        argument_defaults: None,
        source: "uuidv7_interval",
    },
];
