//
// Unified Query Algebra
//
// Copyright (c) 2023-2026 Cognica, Inc.
//

//! `PostgreSQL` 18 built-in routine metadata exposed through the virtual catalogs.

#[derive(Debug, Clone, Copy)]
pub(super) struct BuiltinRoutineCatalogEntry {
    pub(super) oid: i64,
    pub(super) name: &'static str,
    pub(super) kind: &'static str,
    pub(super) strict: bool,
    pub(super) volatility: &'static str,
    pub(super) parallel: &'static str,
    pub(super) leakproof: bool,
    pub(super) return_type: i64,
    pub(super) argument_types: &'static [i64],
    pub(super) argument_names: &'static [&'static str],
    pub(super) default_arguments: usize,
    pub(super) argument_defaults: Option<&'static str>,
    pub(super) source: &'static str,
}

impl BuiltinRoutineCatalogEntry {
    pub(super) const fn language(self) -> i64 {
        match self.oid {
            1810 | 1811 => 14,
            _ => 12,
        }
    }

    pub(super) fn sql_body(self) -> Option<String> {
        let (function_oid, parameter_type, collation_oid) = match self.oid {
            1810 => (720, 17, 0),
            1811 => (1374, 25, 100),
            _ => return None,
        };
        let mut body = String::from(BIT_LENGTH_SQL_BODY_PREFIX);
        body.push_str(&function_oid.to_string());
        body.push_str(BIT_LENGTH_SQL_BODY_AFTER_FUNCTION);
        body.push_str(&collation_oid.to_string());
        body.push_str(BIT_LENGTH_SQL_BODY_AFTER_INPUT_COLLATION);
        body.push_str(&parameter_type.to_string());
        body.push_str(BIT_LENGTH_SQL_BODY_AFTER_PARAMETER_TYPE);
        body.push_str(&collation_oid.to_string());
        body.push_str(BIT_LENGTH_SQL_BODY_SUFFIX);
        Some(body)
    }
}

const BIT_LENGTH_SQL_BODY_PREFIX: &str = concat!(
    "{QUERY :commandType 1 :querySource 0 :canSetTag true :utilityStmt <> ",
    ":resultRelation 0 :hasAggs false :hasWindowFuncs false :hasTargetSRFs false ",
    ":hasSubLinks false :hasDistinctOn false :hasRecursive false :hasModifyingCTE false ",
    ":hasForUpdate false :hasRowSecurity false :hasGroupRTE false :isReturn true :cteList <> ",
    ":rtable <> :rteperminfos <> :jointree {FROMEXPR :fromlist <> :quals <>} ",
    ":mergeActionList <> :mergeTargetRelation 0 :mergeJoinCondition <> ",
    ":targetList ({TARGETENTRY :expr {OPEXPR :opno 514 :opfuncid 141 :opresulttype 23 ",
    ":opretset false :opcollid 0 :inputcollid 0 :args ({FUNCEXPR :funcid "
);
const BIT_LENGTH_SQL_BODY_AFTER_FUNCTION: &str = concat!(
    " :funcresulttype 23 :funcretset false :funcvariadic false :funcformat 0 ",
    ":funccollid 0 :inputcollid "
);
const BIT_LENGTH_SQL_BODY_AFTER_INPUT_COLLATION: &str =
    " :args ({PARAM :paramkind 0 :paramid 1 :paramtype ";
const BIT_LENGTH_SQL_BODY_AFTER_PARAMETER_TYPE: &str = " :paramtypmod -1 :paramcollid ";
const BIT_LENGTH_SQL_BODY_SUFFIX: &str = concat!(
    " :location -1}) :location -1} {CONST :consttype 23 :consttypmod -1 :constcollid 0 ",
    ":constlen 4 :constbyval true :constisnull false :location -1 ",
    ":constvalue 4 [ 8 0 0 0 0 0 0 0 ]}) :location -1} :resno 1 :resname <> ",
    ":ressortgroupref 0 :resorigtbl 0 :resorigcol 0 :resjunk false}) :override 0 ",
    ":onConflict <> :returningOldAlias <> :returningNewAlias <> :returningList <> ",
    ":groupClause <> :groupDistinct false :groupingSets <> :havingQual <> :windowClause <> ",
    ":distinctClause <> :sortClause <> :limitOffset <> :limitCount <> :limitOption 0 ",
    ":rowMarks <> :setOperations <> :constraintDeps <> :withCheckOptions <> ",
    ":stmt_location -1 :stmt_len -1}"
);

const FALSE_NODE: &str = "({CONST :consttype 16 :consttypmod -1 :constcollid 0 :constlen 1 :constbyval true :constisnull false :location -1 :constvalue 1 [ 0 0 0 0 0 0 0 0 ]})";

pub(super) const PG18_BUILTIN_ROUTINES: &[BuiltinRoutineCatalogEntry] = &[
    BuiltinRoutineCatalogEntry {
        oid: 6381,
        name: "array_reverse",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_reverse",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6388,
        name: "array_sort",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_sort",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6389,
        name: "array_sort",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277, 16],
        argument_names: &["array", "descending"],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_sort_order",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6390,
        name: "array_sort",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277, 16, 16],
        argument_names: &["array", "descending", "nulls_first"],
        default_arguments: 0,
        argument_defaults: None,
        source: "array_sort_order_nulls_first",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1810,
        name: "bit_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1811,
        name: "bit_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6412,
        name: "casefold",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "casefold",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1372,
        name: "char_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[1042],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "bpcharlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1381,
        name: "char_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "textlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1367,
        name: "character_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[1042],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "bpcharlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1369,
        name: "character_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "textlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6364,
        name: "crc32",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: true,
        return_type: 20,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "crc32_bytea",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6365,
        name: "crc32c",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: true,
        return_type: 20,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "crc32c_bytea",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6383,
        name: "gamma",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 701,
        argument_types: &[701],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "dgamma",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6384,
        name: "lgamma",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 701,
        argument_types: &[701],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "dlgamma",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1317,
        name: "length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "textlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1318,
        name: "length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[1042],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "bpcharlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2010,
        name: "length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "byteaoctetlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3261,
        name: "json_strip_nulls",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 114,
        argument_types: &[114, 16],
        argument_names: &["target", "strip_in_arrays"],
        default_arguments: 1,
        argument_defaults: Some(FALSE_NODE),
        source: "json_strip_nulls",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3262,
        name: "jsonb_strip_nulls",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 3802,
        argument_types: &[3802, 16],
        argument_names: &["target", "strip_in_arrays"],
        default_arguments: 1,
        argument_defaults: Some(FALSE_NODE),
        source: "jsonb_strip_nulls",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2050,
        name: "max",
        kind: "a",
        strict: false,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6373,
        name: "max",
        kind: "a",
        strict: false,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2249,
        argument_types: &[2249],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6395,
        name: "max",
        kind: "a",
        strict: false,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 17,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2311,
        name: "md5",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: true,
        return_type: 25,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "md5_text",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2321,
        name: "md5",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: true,
        return_type: 25,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "md5_bytea",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2051,
        name: "min",
        kind: "a",
        strict: false,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2277,
        argument_types: &[2277],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6374,
        name: "min",
        kind: "a",
        strict: false,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 2249,
        argument_types: &[2249],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6396,
        name: "min",
        kind: "a",
        strict: false,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 17,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "aggregate_dummy",
    },
    BuiltinRoutineCatalogEntry {
        oid: 720,
        name: "octet_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "byteaoctetlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1374,
        name: "octet_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "textoctetlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1375,
        name: "octet_length",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 23,
        argument_types: &[1042],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "bpcharoctetlen",
    },
    BuiltinRoutineCatalogEntry {
        oid: 1598,
        name: "random",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "r",
        leakproof: false,
        return_type: 701,
        argument_types: &[],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "drandom",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6339,
        name: "random",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "r",
        leakproof: false,
        return_type: 23,
        argument_types: &[23, 23],
        argument_names: &["min", "max"],
        default_arguments: 0,
        argument_defaults: None,
        source: "int4random",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6340,
        name: "random",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "r",
        leakproof: false,
        return_type: 20,
        argument_types: &[20, 20],
        argument_names: &["min", "max"],
        default_arguments: 0,
        argument_defaults: None,
        source: "int8random",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6341,
        name: "random",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "r",
        leakproof: false,
        return_type: 1700,
        argument_types: &[1700, 1700],
        argument_names: &["min", "max"],
        default_arguments: 0,
        argument_defaults: None,
        source: "numeric_random",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6382,
        name: "reverse",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 17,
        argument_types: &[17],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "bytea_reverse",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3062,
        name: "reverse",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[25],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "text_reverse",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6330,
        name: "to_bin",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[23],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_bin32",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6331,
        name: "to_bin",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[20],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_bin64",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2089,
        name: "to_hex",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[23],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_hex32",
    },
    BuiltinRoutineCatalogEntry {
        oid: 2090,
        name: "to_hex",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[20],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_hex64",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6332,
        name: "to_oct",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[23],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_oct32",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6333,
        name: "to_oct",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 25,
        argument_types: &[20],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "to_oct64",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6342,
        name: "uuid_extract_timestamp",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 1184,
        argument_types: &[2950],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "uuid_extract_timestamp",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6343,
        name: "uuid_extract_version",
        kind: "f",
        strict: true,
        volatility: "i",
        parallel: "s",
        leakproof: false,
        return_type: 21,
        argument_types: &[2950],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "uuid_extract_version",
    },
    BuiltinRoutineCatalogEntry {
        oid: 3432,
        name: "gen_random_uuid",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "s",
        leakproof: false,
        return_type: 2950,
        argument_types: &[],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "gen_random_uuid",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6428,
        name: "uuidv4",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "s",
        leakproof: false,
        return_type: 2950,
        argument_types: &[],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "gen_random_uuid",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6429,
        name: "uuidv7",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "s",
        leakproof: false,
        return_type: 2950,
        argument_types: &[],
        argument_names: &[],
        default_arguments: 0,
        argument_defaults: None,
        source: "uuidv7",
    },
    BuiltinRoutineCatalogEntry {
        oid: 6430,
        name: "uuidv7",
        kind: "f",
        strict: true,
        volatility: "v",
        parallel: "s",
        leakproof: false,
        return_type: 2950,
        argument_types: &[1186],
        argument_names: &["shift"],
        default_arguments: 0,
        argument_defaults: None,
        source: "uuidv7_interval",
    },
];
